account/urls.py
from . import views
from django.urls import path

app_name = "account"

urlpatterns = [
    path('dashboard/',views.Dashboard,name="dashboard"),
    path('dashboard/<args>/',views.Dashboard,name="Dashboard2"),
    path('login/',views.login_view,name="google_login"),
    path('bill/',views.bill,name="bill"),
    path('change_password/',views.change_password,name="change_password"),
    path('register/',views.register_view,name="register_view"),
    path('logout/',views.logout_view,name="logout_view"),
    path('cart_detail/',views.cart_detail,name="cart_detail"),
    path('my_account/',views.customer_account,name="customer_account"),
    path('my_account/<args>/',views.customer_account,name="customer_account2")
]

blog/urls.py
from . import views
from django.urls import path

app_name = "blog"

urlpatterns = [
    path('blog/',views.blog,name="blog"),
    path('blog/<cate>/',views.blog,name="blog2"),
    path('blog_detail/<slug>/',views.blog_detail,name="blog_detail"),
    path('addblog/',views.AddBlog,name="AddBlog")
]

index/urls.py
from . import views
from django.urls import path

app_name = "index"

urlpatterns = [
    path('',views.index,name="index"),
    path('contact/',views.contact,name="contact"),
    path('needed_items/',views.place_order_list,name="place_order_list"),
    path('needed_item/<CATE>/',views.place_order_list,name="place_order_list2"),
    path('main_needed_item_view/',views.main_needed_item_view,name='main_needed_item_view'),
    path('edit_needed_item_form/<int:id>/',views.edit_needed_item_form,name="edit_needed_item_form"),
    path('about/',views.about,name="about"),
    path('subscribe/',views.Subscribe,name="Subscribe"),
    path('unsubscribe/',views.unsubscribe,name="unsubscribe"),
    path('terms_conditions/',views.terms_conditions,name="terms_conditions")
]

music/urls.py
#Author Isaac Kakodwa
from . import views
from django.urls import path

app_name = "music"

urlpatterns = [
    path('music/',views.music,name="music"),
    path('music/<args_1>/',views.music,name="music_1"),
    path('main_music/',views.main_music,name="main_music"),
    path('main_music2/<args>/',views.main_music,name="main_music_2"),
    path('music_2/<other_args>/',views.music,name="music_2"),
    path('user_music_list/',views.user_music_list,name='user_music'),
    path('user_music_list2/<args_M>/',views.user_music_list,name='user_music2'),
    path('album_list/<CATEGORY>/',views.album_list,name="album_list"),
    path('album_list2/<TOP_TEN>/',views.album_list,name="album_top_ten"),
    path('album_list_detail/<slug>/',views.album_list_detail,name="album_list_detail"),
    path('album_list_detail2/<slug_2>/',views.album_list_detail,name="album_list_detail2"),
    path('create_album/',views.create_album,name="create_album"),
    path('add_track',views.add_track,name="add_track"),
    path('edit_track/<int:edit_track_id>/',views.add_track,name="edit_track"),
    path('add_track/<slug>/',views.add_track,name="add_track2"),
    path('music_detail/<slug>/',views.music_detail,name="music_detail"),
    path('add_youtube_feed/',views.add_youtube_feed,name="add_youtube_feed"),
    path('youtube_feed_list/',views.youtube_feed_list,name="youtube_feed_list"),
    path('youtube_feed/<CATE>/',views.youtube_feed_list,name="youtube_feed_CATE")
]

mzeebies/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django .conf.urls. static import static
from django .conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls')),
    path('help/',include('help.urls')),
    path('blog/',include('blog.urls')),
    path('products/',include('products.urls')),
    path('music/',include('music.urls')),
    path('account/',include('account.urls')),
    path('cart/',include('cart.urls')),
    path('vendor/',include('vendor.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    #path("stripe/", include("djstripe.urls", namespace="djstripe")),
    path('paypal/', include('paypal.standard.ipn.urls')),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password_reset.html',
             subject_template_name='account/password_reset_subject.txt',
             email_template_name='account/password_reset_email.html',
             # success_url='/login/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]

#handler404 = views.error_404
#handler500 = views.error_500


urlpatterns+=staticfiles_urlpatterns()

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from . import views
from django.urls import path

app_name = "products"

urlpatterns = [
    path('shop/',views.mainshop,name="mainshop"),#for main shop
    path('shop/<args_>/',views.mainshop,name="mainshop2"),# for categories
    path('mainshop22/<args_2>/',views.mainshop,name="type"),
    path('deals_payment_form/<slug>/',views.Deal_payment_form,name="deal_payment_form"),
    path('additem/<int:id>/',views.additem,name="additem"),
    path('additem_msg/',views.additem_msg,name="additem_msg"),
    path('Edit/<slug>/',views.additem,name="edit"),
    path('item_view/',views.item_view,name="item_view"),
    path('additemBanner/',views.additemBanner,name="banner"),
    path('additemBanner/<int:args>/',views.additemBanner,name="banner_edit"),
    path('detail/<slug>/',views.detail,name="detail"),
    path('additemImage/<slug>/',views.additemImage,name="additemImage"),
    path('category_v/',views.category_v,name="category_v"),
    path('upload_brand/',views.upload_brand_img,name="upload_brand"),
    path('timer/',views.timer,name="timer"),
    path('delete/<slug>/',views.delete_item,name="delete_item"),
    path('delete/<int:id>/',views.delete_brand,name="delete_brand"),
    path('remove_category/',views.remove_category,name="remove_category")

]

music/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse,HttpResponseRedirect
from django.urls import reverse
from django.template.loader import render_to_string
from django.conf import settings
from django.contrib.auth.decorators import login_required
from . forms import AlbumForm,MusicForm,youtubefeed_form
from vendor.models import vendor
from products.models import product,category_banner,Brand,Categories 
from . models import Album,Music,Youtubefeed
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from vendor.models import vendor,BillPlan,vendor_bill_plan
from index.snipt import cart_count,send_html_mail,vendor_account,added_sucessfully_msg,popups_advert


def music(request,args_1=None,other_args=None):#music home page
	context = {}

	context['search_placeholder'] = "Search Music"
	context['music_image'] = "show_music_bacground_image"

	cart_count(request.user,context)
	vendor_account(context,request)
	context['popular'] = product.objects.all().order_by('-view')

	album = Album.objects.all()
	context['album'] = album

	youtubefeed = Youtubefeed.objects.all()
	context['youtubefeed'] = youtubefeed


	if other_args == "downloads":
		context['title'] = 'Most downloaded'
		tracks = Music.objects.all().order_by('-vote')

	elif other_args == 'Track Top 12':
		context['title'] = 'Top 12 | Most rated'
		tracks = Music.objects.filter(ratings__isnull=False).order_by('-ratings__average')

	elif other_args == 'New artist':
		context['title'] = 'New artist'
		tracks = Music.objects.filter(first_artist=True).order_by('-updated_at')

	elif args_1:
		context['title'] = args_1
		tracks = Music.objects.filter(genre=args_1).order_by('-updated_at')

	else:
		context['title'] = "Music"
		tracks = Music.objects.all().order_by('-updated_at')

	

	query =request.GET.get('q')

	if request.session.has_key('q'):
		quer = request.session['q']
		context['title'] = quer 

		tracks = tracks.filter(Q(title__icontains=quer)|
			                   Q(genre__icontains=quer)).distinct().order_by('-updated_at')
		del request.session['q']

	if query:
		context['title'] = query
		tracks = tracks.filter(Q(genre__icontains=query)|
			                   Q(title__icontains=query)).distinct().order_by('-updated_at')


	page = request.GET.get('page', 1)
	paginator = Paginator(tracks,12)

	try:
		tracks = paginator.page(page)
	except PageNotAnInteger:
		tracks = paginator.page(1)
	except EmptyPage:
		tracks = paginator.page(paginator.num_pages)

	context['tracks'] = tracks

	if request.is_ajax() and request.GET.get('pops'):#Popups/needed items ajax
		popups_advert(request,context)
		html = render_to_string('index/selected_place_order.html',context,request=request)
		return JsonResponse({'data':html})

	return render(request,'music/music.html',context)

def album_list(request,CATEGORY=None,TOP_TEN=None):
	context = {}
	context['music_image'] = "show_music_bacground_image"

	query =request.GET.get('q')

	if request.session.has_key('added_sucessfuly_msg'):
		context['added_sucessfuly_msg'] = request.session['added_sucessfuly_msg']
		del request.session['added_sucessfuly_msg']
	
	context['search_placeholder'] = "Search Album,Riddim,artist"
	context['popular'] = product.objects.all().order_by('-view')

	cart_count(request.user,context)
	vendor_account(context,request)

	youtubefeed = Youtubefeed.objects.all()
	context['youtubefeed'] = youtubefeed

	if CATEGORY =="Album":
		context['title'] = "Album list"
		album = Album.objects.filter(category="Album").order_by('-updated_at')
	elif CATEGORY == "Riddim":
		context['title'] = "Riddim list"
		album = Album.objects.filter(category="Riddim").order_by('-updated_at')
	elif TOP_TEN == "Album_top_12":
		context['title'] = "Album top 12"
		album = Album.objects.filter(category="Album",ratings__isnull=False).order_by('-ratings__average')
	elif TOP_TEN == "Cover_top_12":
		context['title'] = "Cover top 12"
		album = Album.objects.filter(category="Cover",ratings__isnull=False).order_by('-ratings__average')
	elif TOP_TEN == "Riddim_top_12":
		context['title'] = "Riddim top 12"
		album = Album.objects.filter(category="Riddim",ratings__isnull=False).order_by('-ratings__average')
	else:
		context['title'] = "Cover list"
		album = Album.objects.filter(category="Cover").order_by('-updated_at')


	if request.session.has_key('q'):
		quer = request.session['q']
		context['title'] = quer 

		album = album.filter(Q(title__icontains=quer)|
			                 Q(artist__icontains=quer)).distinct().order_by('-updated_at')
		del request.session['q']
    
	if query:
		context['title'] = query
		album = album.filter(Q(artist__icontains=query)|
			                 Q(title__icontains=query)).distinct().order_by('-updated_at')


	page = request.GET.get('page', 1)
	paginator = Paginator(album,12)


	try:
		album = paginator.page(page)
	except PageNotAnInteger:
		album = paginator.page(1)
	except EmptyPage:
		album = paginator.page(paginator.num_pages)

	context['album'] = album


	if request.is_ajax() and request.GET.get('pops'):#Popups/needed items ajax
		popups_advert(request,context)
		html = render_to_string('index/selected_place_order.html',context,request=request)
		return JsonResponse({'data':html})

	return render(request,'music/album_list.html',context)

def album_list_detail(request,slug=None,slug_2=None):

	context = {}
	context['music_image'] = "show_music_bacground_image"
	context['search_placeholder'] = "Search Music album"
	context['popular'] = product.objects.all().order_by('-view')

	if request.session.has_key('added_sucessfuly_msg'):
		context['added_sucessfuly_msg'] = request.session['added_sucessfuly_msg']
		del request.session['added_sucessfuly_msg']

	cart_count(request.user,context)
	vendor_account(context,request)

	youtubefeed = Youtubefeed.objects.all()
	context['youtubefeed'] = youtubefeed


	if slug_2:
		album = Album.admin_album_objects.get(slug=slug_2)
		context['title'] = album.title 
		context['album'] = album

		track = Music.admin_music_objects.filter(user=request.user,album=album)
		context['track'] = track

	else:
		album = Album.objects.get(slug=slug)
		context['title'] = album.title 
		context['album'] = album

		track = Music.objects.filter(album=album)
		context['track'] = track

	query =request.GET.get('q')
	context['search_placeholder'] = "Search Album,Riddim,artist"
	if query:
		request.session['q'] = query
		return redirect("music:music")

	try:
		get_rack_count = Music.admin_music_objects.filter(album=album).count()
	except Music.DoesNotExist:
		get_rack_count = Music.objects.filter(album=album).count()

	context['album_len'] = get_rack_count

	if request.is_ajax() and request.GET.get('pops'):#Popups/needed items ajax
		popups_advert(request,context)
		html = render_to_string('index/selected_place_order.html',context,request=request)
		return JsonResponse({'data':html})

	return render(request,'music/album_list_detail.html',context)

def music_detail(request,slug=None):

	context = {}
	context['music_image'] = "show_music_bacground_image"
	
	context['popular'] = product.objects.all().order_by('-view')

	cart_count(request.user,context)
	vendor_account(context,request)

	album = Album.objects.all()
	context['album'] = album

	youtubefeed = Youtubefeed.objects.all()
	context['youtubefeed'] = youtubefeed

	tracks = Music.objects.get(slug=slug)
	context['track'] = tracks

	context['title'] = tracks

	related =Music.objects.filter(Q(album=tracks.album)| 
			                             Q(genre =tracks.genre)).distinct()
	context['related_tracks'] = related

	query =request.GET.get('q')
	context['search_placeholder'] = "Search Music"
	if query:
		request.session['q'] = query
		return redirect("music:music")

	if request.is_ajax() and request.GET.get('pops'):#Popups/needed items ajax
		popups_advert(request,context)
		html = render_to_string('index/selected_place_order.html',context,request=request)
		return JsonResponse({'data':html})

	elif request.is_ajax():#downloads increments

		track_id = request.GET.get('data')
		tracks_d = Music.objects.get(id=track_id)
		
		current_downloads = tracks_d.vote
		current_downloads += 1
		tracks_d.vote = current_downloads 
		tracks_d.save()

	return render(request,'music/detail.html',context)

@login_required(login_url="account:google_login")
def create_album(request):
	context = {}
	context['music_image'] = "show_music_bacground_image"
	context['title'] = "Add album"

	cart_count(request.user,context)
	vendor_account(context,request)


	try:#for allowing user to add item if they  settle their bills
		Paid_bill   = BillPlan.objects.get(user=request.user)
		context['bill'] = Paid_bill

		Num_of_item = Paid_bill.item_num
		added_item  = Paid_bill.item_num2

		if added_item < Num_of_item:


			if request.method == "POST":

				form = AlbumForm(request.POST,request.FILES)

				if form.is_valid():
					instance = form.save()
					instance.vendor = vendor.objects.get(user=request.user)
					instance.save()

					Paid_bill.item_num2 += 1
					Paid_bill.save()

					return redirect('music:add_track')

			else:
				form = AlbumForm()

		else:
			request.session['bill_expired'] = "Your items rich maxmum!!"
			return redirect('account:bill')

	except BillPlan.DoesNotExist:
		return redirect('account:bill')

	context['form'] = form
	return render(request,'index/form.html',context)

@login_required(login_url="account:google_login")
def add_track(request,slug=None,edit_track_id=None):
	context = {}
	context['music_image'] = "show_music_bacground_image"
	context['title'] = "Add track/audio"

	cart_count(request.user,context)
	vendor_account(context,request)

	Vendor = vendor.objects.get(user=request.user)

	if slug:
		album = Album.admin_album_objects.get(slug=slug)
	else:
		album = Album.admin_album_objects.filter(vendor=Vendor).last()


	try:#for allowing user to add item if they  settle their bills
		Paid_bill   = BillPlan.objects.get(user=request.user)

music/templates/music/category.html
<h4 style="color:orange;"><strong>Categories</strong></h4>

<div class="p-2 mb-2 rounded" style="background-color:rgb(241,246,247);">
	<a href="{% url 'music:music' %}">All music</a>
	<a href="{% url 'music:music_1' 'Raggie' %}">Raggie</a>
    <a href="{% url 'music:music_1' 'Dancehall' %}">Dancehall</a>
    <a href="{% url 'music:music_1' 'House' %}">House</a>
    <a href="{% url 'music:music_1' 'Afro House' %}">Afro House</a>
    <a href="{% url 'music:music_1' 'Amapiano' %}">Amapiano</a>
    <a href="{% url 'music:music_1' 'Gospel' %}">Gospel</a>
    <a href="{% url 'music:music_1' 'Hip Hop' %}">Hip Hop</a>
    <a href="{% url 'music:music_1' 'Trap' %}">Trap</a>
    <a href="{% url 'music:music_1' 'Poetry' %}">Poetry/Poem</a>
    <a href="{% url 'music:music_1' 'Beats' %}">Beats</a>
</div>

<div class="p-2 rounded" style="background-color:rgb(241,246,247);">
    <a href="{% url 'music:music_2' 'New artist' %}">New artist</a>
    <a href="{% url 'music:music_2' 'Track Top 12' %}">Track Top 12 </a>
    <a href="{% url 'music:music_2' 'downloads' %}">Most downloaded</a><hr>
    <a href="{% url 'music:album_list' 'Album'%}">Album</a>
    <a href="{% url 'music:album_top_ten' 'Album_top_12'%}">Album top 12</a><hr>
    <a href="{% url 'music:album_list' 'Cover'%}">Cover</a>
    <a href="{% url 'music:album_top_ten' 'Cover_top_12'%}">Cover top 12 </a><hr>
    <a href="{% url 'music:album_list' 'Riddim'%}">Riddim</a>
    <a href="{% url 'music:album_top_ten' 'Riddim_top_12'%}">Riddim top 12</a>
</div>

music/templates/music/main_music.html
{% extends "index/base.html"%}
{% load static %}
{% load crispy_forms_tags %}


    
{% block body %}

{% include 'index/header.html '%}

<section class="my-1">
   <div class="container" id="inner_nav">
      <a href="{% url 'index:index' %}">Home</a>
      <a href="javascript:void(0);">/</a>
      <a href="{% url 'account:dashboard' %}">Dashboard</a>
      <a href="javascript:void(0);">/</a>
      <a href="#">Music</a>


      <div style="float:right;">
         <a id="display_category" 
            onclick="display_category();" 
            href="javascript:void(0);">
              <img src="{% static 'img/cat.png' %}" height="20">
          </a>
          <a id="hide_category" 
             href="javascript:void(0);" 
             onclick="hide_category();">
              <img src="{% static 'img/cat2.png' %}" height="20">
           </a>
      </div>
    
   </div><hr>
</section>


<!--<section class="my-2" id="brand_desktop_view">
    {% include 'music/album.html'%}
</section>-->

<section class="my-2">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-lg-2" id="main_category">
				<div class="p-2 rounded" id="music_category" style="background-color:rgb(241,246,247);">
            <h4><strong>Music manager</strong></h4><hr>
					  <a href="{% url 'music:main_music' %}">Approved track/s</a><hr>
            <a href="{% url 'music:main_music_2' 'Non approved track' %}">Non approved track/s</a><hr>
            <a href="{% url 'music:main_music_2' 'Rejected track' %}">Rejected track/s</a><hr>
				</div>
			</div>

			<div class="col-sm-12 col-lg-10">
				<section id="ik_music_manager_area">
				    <div class="row">
				    	 {% for track in tracks %}
				    	    <div class="col-sm-12 col-lg-3">
				    	    	<div class="my-2 main_music_outer" onmouseover="music_manager('{{track.slug}}');" onmouseout="music_manager2('{{track.slug}}');">
                      <p style="color:orange;"><strong>{{track}}</strong></p>
				    	    		<a href="{% url 'music:music_detail' track.slug %}">
                          <img src="{{track.file.url}}" class="d-block w-100 rounded">       
                      </a>
				    	    

                      <div class="main_music_inner rounded p-2" id="ikmusic_{{track.slug}}">
                          <audio class="d-block w-100 rounded mb-4" id="ik_audio" controls="controls">
                             <source src="{{track.mp3.url}}" type="audio/mpeg">
                          </audio><hr>

                          {% if track.allowed == False %}
                          <a onclick="Aprove_music('{{track.id}}');" id="custom_btn" href="javascript:void(0);">Approve</a><hr>
                          {% endif %}

                          <a onclick="disapprove_music('{{track.id}}');" id="custom_btn2" href="javascript:void(0);">Disapprove</a><hr>
                          <a onclick="delete_music('{{track.id}}');" href="javascript:void(0);">Delete</a>
                      </div>
                      
				    	    	</div>
                  
				    	    </div>
				    	 {% empty %}
				    	     <div class="col-sm-12">
                      {% include 'index/error.html' %}
                    </div>
				    	 {% endfor %}
				    </div>
<!--______________________________pagination_______________________________-->
                            <div class="my-4">
                                <div class="pagination">
                                    <span class="step-links">
                                        {% if tracks.has_previous %}
                                        <a href="?page=1">&laquo;</a>
                                        <a href="?page={{ tracks.previous_page_number }}">
                                            <i class="fa fa-arrow-left" aria-hidden="true"></i>
                                         </a>

                                        {% endif %}

                                        <span class="current">
                                        Page {{tracks.number }} of {{tracks.paginator.num_pages }}.
                                        </span>

                                        {% if tracks.has_next %}
                                        <a href="?page={{tracks.next_page_number }}">
                                            <i class="fa fa-arrow-right" aria-hidden="true"></i>
                                        </a>
                                        <a href="?page={{tracks.paginator.num_pages }}">&raquo;</a>
                                        {% endif %}
                                    </span>
                                </div>
                            </div>
<!--___________________________________________________________________-->
				</section>
		   </div>
	</div>
</section>


{% endblock %}

music/templates/music/user_music.html
{% extends "index/base.html"%}
{% load static %}
{% load crispy_forms_tags %}


    
{% block body %}




{% include 'index/header.html '%}

<section class="my-1">
   <div class="container" id="inner_nav">
      <a href="{% url 'index:index' %}">Home</a>
      <a href="javascript:void(0);">/</a>
      <a href="{% url 'account:customer_account' %}">My account</a>
      <a href="javascript:void(0);">/</a>
      <a href="{% url 'vendor:vendor' %}">Vendor</a>
      <a href="javascript:void(0);">/</a>
      <a href="#">Your music</a>


      <div style="float:right;">
         <a id="display_category" 
            onclick="display_category();" 
            href="javascript:void(0);">
              <img src="{% static 'img/cat.png' %}" height="20">
          </a>
          <a id="hide_category" 
             href="javascript:void(0);" 
             onclick="hide_category();">
              <img src="{% static 'img/cat2.png' %}" height="20">
           </a>
      </div>
    
   </div><hr>
</section>


<!--<section class="my-2" id="brand_desktop_view">
    {% include 'music/album.html'%}
</section>-->

<section class="my-2">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-lg-2" id="main_category">
				<div class="p-2 rounded" id="music_category" style="background-color:rgb(241,246,247);">
            <h4><strong>Music manager</strong></h4><hr>
            <a href="{% url 'music:user_music2' 'Proved song' %}">Approved song</a><hr>
            <a href="{% url 'music:user_music2' 'Non proved song' %}">Non  approved song</a><hr>
            <a href="{% url 'music:user_music2' 'Your album list' %}"> Approved album list</a><hr>
            <a href="{% url 'music:user_music2' 'Non aproved album' %}">Non approved album</a><hr>
				</div>
			</div>

			<div class="col-sm-12 col-lg-10">

        {% if for_album %}
        <section>

            <div class="row">
               {% for album in album %}
                  <div class="col-sm-12 col-lg-3">
                    <div class="my-2">
                      <p style="color:orange;"><strong>{{album}}</strong></p>
                      {% if for_non_album %}
                      <a href="{% url 'music:album_list_detail2' album.slug %}">
                          <img src="{{album.file.url}}" class="d-block w-100 rounded-top">       
                      </a> 
                      {% else %}
                      <a href="{% url 'music:album_list_detail' album.slug %}">
                          <img src="{{album.file.url}}" class="d-block w-100 rounded-top">       
                      </a>
                      {% endif %}

                    </div>
                    
                  </div>
               {% empty %}
                   <div class="col-sm-12">
                                {% include 'index/error.html' %}
                             </div>
               {% endfor %}
            </div>
<!--______________________________pagination_______________________________-->
                            <div class="my-4">
                                <div class="pagination">
                                    <span class="step-links">
                                        {% if album.has_previous %}
                                        <a href="?page=1">&laquo;</a>
                                        <a href="?page={{ album.previous_page_number }}">
                                            <i class="fa fa-arrow-left" aria-hidden="true"></i>
                                         </a>

                                        {% endif %}

                                        <span class="current">
                                        Page {{ album.number }} of {{album.paginator.num_pages }}.
                                        </span>

                                        {% if album.has_next %}
                                        <a href="?page={{album.next_page_number }}">
                                            <i class="fa fa-arrow-right" aria-hidden="true"></i>
                                        </a>
                                        <a href="?page={{album.paginator.num_pages }}">&raquo;</a>
                                        {% endif %}
                                    </span>
                                </div>
                            </div>
<!--___________________________________________________________________-->
        </section>

        {% else %}

				<section id="ik_music_manager_area">
            {% if deleted_sucessfuly_msg %}
                 <p style="color:red;">{{deleted_sucessfuly_msg}}</p>
            {% endif %}
				    <div class="row" id="ik_music_list">
				    	 {% for track in track %}
				    	    <div class="col-sm-12 col-lg-3">
				    	    	<div class="my-2 " onmouseover="music_manager('{{track.slug}}');" onmouseout="music_manager2('{{track.slug}}');">
                      <p style="color:orange;"><strong>{{track}}</strong><a class="close" onclick="disply_music_button('{{track.id}}');" href="javascript:void(0);">:</a></p>
				    	    		   
                         {% if for_non_music %}
                          
                          <img src="{{track.file.url}}" class="d-block w-100 rounded-top">

                          {% else %}  

                          <a href="{% url 'music:music_detail' track.slug %}">
                          <img src="{{track.file.url}}" class="d-block w-100 rounded-top"></a>

                          {% endif %}    

                          <audio class="d-block w-100 rounded-bottom" id="ik_audio" controls="controls">
                        <source src="{{track.mp3.url}}" type="audio/mpeg">
                      </audio>
                       

                       <div  id="music_detail_button{{track.id}}" class="music_detail_button">
                          <div style="background-color:orange;" class="text-center mr-1 rounded p-3">

                            {% if track.rejected == True %}
                              
                                <a class="p-1 rounded text-left" style="color:red;" href="javascript:void(0);">Rejected</a>
                             
                            {% endif %}

                            <a style="color:red;" class="close" onclick="disply_music_button('{{track.id}}');" href="javascript:void(0);">X</a><hr>
                             <a onclick="delete_music('{{track.id}}');" href="javascript:void(0);">Delete</a><br>

                             {% if user_bill.due_date != None %}
                             <a href="{% url 'music:edit_track' track.id%}">Edit</a>
                             {% else %}
                             <a href="{% url 'account:bill'%}">Edit</a>
                             {% endif %}
                          </div>
                      </div> 
				    	    	</div>

				    	    </div>
				    	 {% empty %}
				    	     <div class="col-sm-12">
                      {% include 'index/error.html' %}
                    </div>
				    	 {% endfor %}
				    </div>
				</section>
<!--______________________________pagination_______________________________-->
                            <div class="my-4">
                                <div class="pagination">
                                    <span class="step-links">
                                        {% if track.has_previous %}
                                        <a href="?page=1">&laquo;</a>
                                        <a href="?page={{ track.previous_page_number }}">
                                            <i class="fa fa-arrow-left" aria-hidden="true"></i>
                                         </a>

                                        {% endif %}

                                        <span class="current">
                                        Page {{ track.number }} of {{track.paginator.num_pages }}.
                                        </span>

                                        {% if track.has_next %}
                                        <a href="?page={{track.next_page_number }}">
                                            <i class="fa fa-arrow-right" aria-hidden="true"></i>
                                        </a>
                                        <a href="?page={{track.paginator.num_pages }}">&raquo;</a>
                                        {% endif %}
                                    </span>
                                </div>
                            </div>
<!--___________________________________________________________________-->
        {% endif %}
		   </div>
	</div>
</section>


{% endblock %}