account/urls.py
from . import views
from django.urls import path

app_name = "account"

urlpatterns = [
    path('dashboard/',views.Dashboard,name="dashboard"),
    path('dashboard/<args>/',views.Dashboard,name="Dashboard2"),
    path('login/',views.login_view,name="google_login"),
    path('bill/',views.bill,name="bill"),
    path('change_password/',views.change_password,name="change_password"),
    path('register/',views.register_view,name="register_view"),
    path('logout/',views.logout_view,name="logout_view"),
    path('cart_detail/',views.cart_detail,name="cart_detail"),
    path('my_account/',views.customer_account,name="customer_account"),
    path('my_account/<args>/',views.customer_account,name="customer_account2")
]

blog/urls.py
from . import views
from django.urls import path

app_name = "blog"

urlpatterns = [
    path('blog/',views.blog,name="blog"),
    path('blog/<cate>/',views.blog,name="blog2"),
    path('blog_detail/<slug>/',views.blog_detail,name="blog_detail"),
    path('addblog/',views.AddBlog,name="AddBlog")
]

cart/urls.py
from . import views
from django.urls import path

app_name = "cart"

urlpatterns = [
    path('cart/',views.shopingcart,name="cart"),
    path('add_to_cart/<slug>/',views.add_to_cart,name="add_to_cart"),
    path('cart_view/',views.cart_view,name="cart_view"),
    path('remove_cart/<int:id>/',views.remove_cart,name="remove_cart"),
    path('billing/<int:id>/',views.billing,name="billing"),
    path('paypal/<int:id>/',views.paypal,name="paypal"),
    path('stripe/<int:id>/',views.stripe,name="stripe"),
    path('charge/',views.charge_d,name="charge"),
    path('paypal_thax/',views.paypal_thax,name="paypal_thax"),
    path('delivered/',views.delivered,name="delivered"),
    path('Payment_verification/',views.confirm_mobile_payments,name="verify_p"),
    path('Payment_verification/<args>/',views.confirm_mobile_payments,name="verify_p2")
]

index/urls.py
from . import views
from django.urls import path

app_name = "index"

urlpatterns = [
    path('',views.index,name="index"),
    path('contact/',views.contact,name="contact"),
    path('needed_items/',views.place_order_list,name="place_order_list"),
    path('needed_item/<CATE>/',views.place_order_list,name="place_order_list2"),
    path('main_needed_item_view/',views.main_needed_item_view,name='main_needed_item_view'),
    path('edit_needed_item_form/<int:id>/',views.edit_needed_item_form,name="edit_needed_item_form"),
    path('about/',views.about,name="about"),
    path('subscribe/',views.Subscribe,name="Subscribe"),
    path('unsubscribe/',views.unsubscribe,name="unsubscribe"),
    path('terms_conditions/',views.terms_conditions,name="terms_conditions")
]

mzeebies/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django .conf.urls. static import static
from django .conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls')),
    path('help/',include('help.urls')),
    path('blog/',include('blog.urls')),
    path('products/',include('products.urls')),
    path('music/',include('music.urls')),
    path('account/',include('account.urls')),
    path('cart/',include('cart.urls')),
    path('vendor/',include('vendor.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    #path("stripe/", include("djstripe.urls", namespace="djstripe")),
    path('paypal/', include('paypal.standard.ipn.urls')),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password_reset.html',
             subject_template_name='account/password_reset_subject.txt',
             email_template_name='account/password_reset_email.html',
             # success_url='/login/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]

#handler404 = views.error_404
#handler500 = views.error_500


urlpatterns+=staticfiles_urlpatterns()

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from . import views
from django.urls import path

app_name = "products"

urlpatterns = [
    path('shop/',views.mainshop,name="mainshop"),#for main shop
    path('shop/<args_>/',views.mainshop,name="mainshop2"),# for categories
    path('mainshop22/<args_2>/',views.mainshop,name="type"),
    path('deals_payment_form/<slug>/',views.Deal_payment_form,name="deal_payment_form"),
    path('additem/<int:id>/',views.additem,name="additem"),
    path('additem_msg/',views.additem_msg,name="additem_msg"),
    path('Edit/<slug>/',views.additem,name="edit"),
    path('item_view/',views.item_view,name="item_view"),
    path('additemBanner/',views.additemBanner,name="banner"),
    path('additemBanner/<int:args>/',views.additemBanner,name="banner_edit"),
    path('detail/<slug>/',views.detail,name="detail"),
    path('additemImage/<slug>/',views.additemImage,name="additemImage"),
    path('category_v/',views.category_v,name="category_v"),
    path('upload_brand/',views.upload_brand_img,name="upload_brand"),
    path('timer/',views.timer,name="timer"),
    path('delete/<slug>/',views.delete_item,name="delete_item"),
    path('delete/<int:id>/',views.delete_brand,name="delete_brand"),
    path('remove_category/',views.remove_category,name="remove_category")

]

cart/forms.py
from . models import Mobile,Order,OrderItem,item_size_color
from django.contrib.auth.models import User
from django.forms import ModelForm
from PIL import Image
from django import forms
from django.core.files import File


class mobile_form(ModelForm):
  class Meta:
    model = Mobile
    fields =['mobile','name','rep_no','amount']

cart/views.py
from django.shortcuts import render,redirect
from .models import Order,OrderItem,item_size_color
from django.http import HttpResponse,JsonResponse,HttpResponseRedirect
from django.urls import reverse
from django.template.loader import render_to_string
from products.models import product,Categories,Brand
from django.conf import settings
from . forms import mobile_form
from index.snipt import cart_count,send_html_mail,vendor_account,secret_code,popups_advert
from django.contrib.auth.decorators import login_required
from paypal.standard.forms import PayPalPaymentsForm
from vendor.models import vendor_bill_plan
from . models import Mobile, Order,billing_address,shipping_address,Top_seller
#ikpixels.py-facilitator@gmail.com

#import stripe
#stripe.api_key = settings.STRIPE_TEST_SECRET_KEY


def color_size_(Product,Cart,color=None,size=None):
    Item = OrderItem.objects.get(item=Product,cart=Cart)

    try:
        item = item_size_color.objects.filter(item=Item)

        if color and size == None:
            pro = item_size_color(item=Item,color=color)
            pro.save()
        
        elif size and color == None:
            pro = item_size_color(item=Item,size=size)
            pro.save()

        elif size and color:
            pro = item_size_color(item=Item,color=color,size=size)
            pro.save()

    except item_size_color.DoesNotExist:
        if color and size == None:
            item = item_size_color(item=Item,color=color)
            item.save()

        elif size and color == None:
            item = item_size_color(item=Item,size=size)
            item.save()

        elif size and color:
            item = item_size_color(item=Item,color=color,size=size)
            item.save()

#______________________________________________________________________
def get_user_cart(request):
    if request.user.is_authenticated and not request.user.is_anonymous:
        try:
            cart = Order.objects.get(user=request.user,ordered=False,paid_bill=False)

        except Order.DoesNotExist:
            cart = Order(user=request.user)
            cart.save()

    else:
        cart_id = request.session.get('cart_id')
        if not cart_id:
            cart = Order()
            cart.save()
        else:
            cart = Order.objects.get(id=cart_id)
    return cart

def shopingcart(request):
	pass

@login_required(login_url="account:google_login")
def add_to_cart(request,slug=None):

    context = {}

    query =request.GET.get('q')#query 
    if query:
        request.session['q'] = query
        return redirect("products:mainshop")


    if request.is_ajax() and request.GET.get('pops'):#Popups/needed items ajax
        pass
    elif request.is_ajax():

        order = get_user_cart(request)
        item = product.objects.get(slug=slug)

        top_seller = Top_seller(product=item)
        top_seller.save()

        try:
            cart_item = OrderItem.objects.get(item=item,cart=order,vendor=item.user)
            quantity = cart_item.quantity
            quantity += 1
            cart_item.quantity = quantity
            cart_item.save()

            Stock = item.stock # decreasing number of stock
            Stock -= 1
            item.stock = Stock
            item.save()

        except OrderItem.DoesNotExist:
            cart_item = OrderItem(cart=order,item=item,quantity=1,vendor=item.user)
            cart_item.save()

            Stock = item.stock # decreasing number of stock
            Stock -= 1
            item.stock = Stock
            item.save()

        color = request.GET.get('color')
        size  = request.GET.get('size')
        color_size_(item,order,color,size)

    return redirect('cart:cart_view')



@login_required(login_url="account:google_login")
def remove_cart(request, id):
    context ={}

    if request.is_ajax() and request.GET.get('pops'):#Popups/needed items ajax
        pass
    if request.is_ajax():

        cart_item = OrderItem.objects.get(id=id)

        item = product.objects.get(slug=cart_item.item.slug)

        if cart_item.quantity > 1:

            try:
                color_size = item_size_color.objects.filter(item=cart_item).last()

                if color_size:
                    color_size.delete()

            except item_size_color.DoesNotExist:
                pass

            quantity = cart_item.quantity
            quantity -= 1
            cart_item.quantity = quantity
            cart_item.save()

            Stock = item.stock #stock increament
            Stock += 1
            item.stock = Stock
            item.save()

        else:
            try:
                color_size = item_size_color.objects.get(item=cart_item)

                if color_size:
                    color_size.delete()

            except item_size_color.DoesNotExist:
                pass

            cart_item.delete()

            Stock = item.stock #stock increament
            Stock += 1
            item.stock = Stock
            item.save()

        return redirect('cart:cart_view')

def cart_view(request):

    context = {}
    context['title'] = "Your shoping cart"
    context['brand'] = Brand.objects.all()
    vendor_account(context,request)

    query =request.GET.get('q')
    context['search_placeholder'] = "Search product based on name/your district/your area/Category/vendor/brand"
    if query:
        request.session['q'] = query
        return redirect("products:mainshop")


    if request.is_ajax() and request.GET.get('pops'):#Popups/needed items ajax
        popups_advert(request,context)
        html = render_to_string('index/selected_place_order.html',context,request=request)
        return JsonResponse({'data':html})


    if request.user.is_authenticated:
        order_ = get_user_cart(request)
        if order_:
            cart_count(request.user,context)

            query =request.GET.get('q')
            if query:
                request.session['q'] = query
                return redirect("products:mainshop")

            context['currency'] = Categories.objects.all().last()
            order = Order.objects.get(user = request.user,ordered=False,paid_bill = False)


            if order.checkout_stage == True  and order.pyment_method == "stripe" or order.paid_bill == True:
                request.session['finish_payment'] = "Finish your payment please"
                return HttpResponseRedirect(reverse('cart:stripe', args=[order.id]))
                del request.session['finish_payment'] 

            elif order.checkout_stage == True  and order.pyment_method == "paypal" or order.paid_bill == True:
                request.session['finish_payment'] = "Finish your payment please"
                return HttpResponseRedirect(reverse('cart:paypal', args=[order.id]))
                del request.session['finish_payment']

            context['order'] = order
        return render(request,'cart/cart.html',context)

    else:#for anonymous user
        request.session['user_error'] = "Your shoping cart is 0, Start shoping now !!"
        return redirect('products:mainshop')

@login_required(login_url="account:google_login")
def billing(request,id):
    context = {}
    context['title'] = "Checkout"
    cart_count(request.user,context)
    vendor_account(context,request)
   
    query =request.GET.get('q')
    if query:
        request.session['q'] = query
        return redirect("products:mainshop")

    cart = Order.objects.get(user=request.user,ordered=False,paid_bill=False)
    context['cart'] = cart


    if request.is_ajax() and request.GET.get('pops'):#Popups/needed items ajax
        popups_advert(request,context)
        html = render_to_string('index/selected_place_order.html',context,request=request)
        return JsonResponse({'data':html})

    elif request.is_ajax():
        #billing details__________________________
        first_name = request.GET.get('first_name')
        last_name  = request.GET.get('last_name')
        house  = request.GET.get('house')
        country= request.GET.get('country')
        town  = request.GET.get('town')
        suit  = request.GET.get('suit')
        zip_code= request.GET.get('zip')
        phone   = request.GET.get('phone')
        email   = request.GET.get('email')
        Billing = billing_address(user=request.user,
                     first_name=first_name,
                     last_name=last_name,
                     country=country,
                     city=town,
                     street_adress=house,
                     phone=phone,
                     email=email,
                     zip_code=zip_code,
                     apartment=suit).save()


        #shipping details___________________________
        first_name2 = request.GET.get('first_name2')
        last_name2= request.GET.get('last_name2')
        house2  = request.GET.get('house2')
        country2= request.GET.get('country2')
        town2  = request.GET.get('town2')
        suit2  = request.GET.get('suit2')
        zip_code2= request.GET.get('zip2')
        phone2   = request.GET.get('phone2')
        email2   = request.GET.get('email2')
        Billing=shipping_address(user=request.user,
                     first_name=first_name2,
                     last_name=last_name2,
                     country=country2,
                     city=town2,
                     street_adress=house2,
                     phone=phone2,
                     email=email2,
                     zip_code=zip_code2,
                     apartment=suit).save()

        
    return render(request,'cart/billing.html',context)

@login_required(login_url="account:google_login")
def paypal(request,id):
    context = {}

    cart_count(request.user,context)
    vendor_account(context,request)
    
    if request.session.has_key('finish_payment'):
        context['finish_payment'] = request.session['finish_payment']


    cart = Order.objects.get(user=request.user,id=id,ordered=False)
    cart.checkout_stage = True

cart/templates/cart/billing.html
{% extends "index/base.html"%}
{% load static %}
{% load crispy_forms_tags %}


    
{% block body %}

{% include 'index/header.html '%}

<section class="my-1">
   <div class="container" id="inner_nav">
      <a href="{% url 'index:index' %}">Home</a>
      <a href="javascript:void(0);">/</a>
      <a href="{% url 'products:mainshop' %}">Products</a>
      <a href="javascript:void(0);">/</a>
      <a href="{% url 'cart:cart_view' %}">cart</a>
      <a href="javascript:void(0);">/</a>
      <a href="#">Checkout</a>
   </div><hr>
</section>

<!--__________terms & conditions notchecked error___________-->
<div id="terms_error" class="text-center p-2 my-2 alert" style="display:none;">
	
    <div class="p-3 rounded" id="inner_terms_error">
    	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <p class="text-left"><strong  style="color:orange;">Error</strong></p><hr>
         <p style="color:red;">Please make sure terms & conditions is checked before placing order !!!</p>
    </div>
</div>
<!---------------------------------------------------------------->

<section>
	<div class="container">
		
		 <div class="row">
		 	  <div class="col-sm-12 col-lg-8" >
		 	  	   <div class="p-2 rounded mb-2" style="background-color:rgb(241,246,247);">
		 	  	   <form><!--pass---></form>
                   <form id="Billing_form">
                       {% csrf_token %}
                   {% include 'cart/billing_info.html'%}
                   {% include 'cart/shipping_info.html'%}
                   </form>

		 	  	   <div class="p-2" id="shipping_btn">
		 	           <h4 style="color:orange;"><strong>Shipping Details</strong></h4><hr>
		 	           <div class="form-check form-check-inline mx-4">
                            <input class="form-check-input" type="checkbox" id="shiping" value="shiping" onchange="shiping(this);">
                            <label class="form-check-label" for="inlineCheckbox1">Ship to a different address?</label>
                        </div>
		           </div>
		         </div>

		 	  </div>

		 	  <div class="col-sm-12 col-lg-4">
		 	  	 <div class="mb-4 p-2 rounded" style="background-color:rgb(241,246,247);">
		 	  	 	<h4 style="color:orange;"><strong>Cart Total</strong></h4><hr>
                    {% for cart in cart.cart.all %}
		 	  	 	<div class="row">
		 	  	 		 <div class="col">
		 	  	 		 	<p>{{cart}}</p>
		 	  	 		 </div>
		 	  	 		 <div class="col">
		 	  	 		 	 <p>{{cart.item.price}}</p>
		 	  	 		 </div>
		 	  	 	</div>
		 	  	 	{% endfor %}

		 	  	 	<div class="row">
		 	  	 		 <div class="col">
		 	  	 		 	<h4><strong>Total</strong></h4>
		 	  	 		 </div>
		 	  	 		 <div class="col">
		 	  	 		 	 <h4><strong>{{cart.get_total}}</strong></h4>
		 	  	 		 </div>
		 	  	 	</div>
		 	  	 
		 	  	 </div>

		 	  	 <div class="p-2 rounded" style="background-color:rgb(241,246,247);">
		 	  	 	<h4>Payment Method</h4><hr>
		 	  	 	<div class="mx-4">
		 	  	 		{% include 'cart/chechbox.html'%}
		 	  	 	</div>
		 	  	 </div>

		 	  	 <div class="py-2 mt-4">
		 	  	 	 <button class="p-2" onclick="payment('{{cart.id}}');" style="width:100%;" id="custom_cart_btn" id="">Place order</button>
		 	  	 </div>
		 	  </div>
		 </div>

	</div>
</section>



{% endblock %}

cart/templates/cart/cart.html
{% extends "index/base.html"%}
{% load static %}
{% load crispy_forms_tags %}


    
{% block body %}

{% include 'index/header.html '%}


<section class="my-1">
   <div class="container" id="inner_nav">
      <a href="{% url 'index:index' %}">Home</a>
      <a href="javascript:void(0);">/</a>
      <a href="{% url 'products:mainshop' %}">Products</a>
      <a href="javascript:void(0);">/</a>
      <a href="#">cart</a>
   </div><hr>
</section>

<section class="mb-4">
    <div class="container">
       <div class="table-responsive">
        <table class="table table-striped">
            <thead style="background-color:red;color:white;">
               <th></th>
               <th>ITEM</th>
               <th>QT</th>
               <th>PRICE({{currency.currency}})</th>
               <th>TOTAL({{currency.currency}})</th>
            </thead>

            {% for item in order.cart.all %}
               <tr>
                  <td>
                    {% if item.item.file %}
                    <img src="{{item.item.file.url}}" class="mr-2" height="64">
                    {% else %}
                    <img src="{% static 'img/item.png' %}" class="mr-2" height="64">
                    {% endif %}
                     <a onclick="delete_item('{% url 'cart:remove_cart' item.id %}');" style="color:red;" href="javascript:void(0);">
                       <i class="fa fa-trash" aria-hidden="true"></i>
                     </a>
                   </td>
                  <td>{{item}}</td>
                  <td>{{item.quantity}}</td>
                  <td>{{item.item.price}}</td>
                  <td>{{item.get_final_price}}</td>
               </tr>
            {% empty %}
               <tr>
                  <td colspan="7" style="color:red;font-size:30px;">Your cart is empty...</td>
               </tr>
            {% endfor %}
        </table>
      </div>

        <div class="text-right">
           <h1><strong>{{currency.currency}} {{order.get_total}}</strong></h1>
        </div>

        <div class="row my-4">
            <div class="col-sm-6">
              
            </div>
            <div class="col-sm-6 text-right">
                <a id="custom_btn2" class="mr-2 p-2 my-2" href="{% url 'products:mainshop'%}">Continue shoping</a>
                {% if order.get_total is not 0 %}
                <a class="p-2 my-2" id="custom_btn" href="{% url 'cart:billing' order.id %}">Proceed to Checkout</a>
                {% endif %}
            </div>
        </div>
    </div>
</section>


{% if brand %}
{% include 'products/brand.html'%}
{% endif %}

{% endblock %}

cart/templates/cart/charge.html
<p>Thank you</p>

cart/templates/cart/chechbox.html
<div class="form-check">
  <input class="form-check-input" type="radio" name="exampleRadios" id="Stripe" value="Stripe" checked>
  <label class="form-check-label" for="exampleRadios1">
    Mobile
  </label>
</div>
<div class="form-check">
  <input class="form-check-input" type="radio" name="exampleRadios" id="Paypal" value="Paypal">
  <label class="form-check-label" for="exampleRadios2">
    Paypal
  </label>
</div>

<div class="form-check form-check-inline">
  <input class="form-check-input" type="checkbox" id="terms" value="terms" name="terms">
  <label class="form-check-label" for="terms">I’ve read and accept the <a style="color:orange;" href="{% url 'index:terms_conditions'%}">terms & conditions</a></label>
</div>

cart/templates/cart/confirm_payment.html
{% extends "index/base.html"%}
{% load static %}

{% block body %}
{% include 'index/header.html '%}

<section class="my-1">
	 <div class="container" id="inner_nav">
	 	  <a href="{% url 'index:index' %}">Home</a>
	 	  <a href="javascript:void(0);">/</a>
	 	  <a href="{% url 'account:dashboard' %}">Myaccount</a>
	 	  <a href="javascript:void(0);">/</a>
	 	  <a href="#">Mobile payment</a>
	 </div><hr>
</section>

<section class="my-2">
	<div class="container">
		<div class="row">
			 <div class="col-sm-12 col-lg-2" id="dashboard_menu">
			 	<div class="p-2">
			 		<h4>Payment method</h4><hr>
			 		<a href="{% url 'cart:verify_p'%}">All Payments</a><hr>
			 		<a href="{% url 'cart:verify_p2' 'airtel'%}"> <img src="{% static 'img/airtel.jpg' %}" class="rounded" width="20">Airtel money</a><hr>
			 		<a href="{% url 'cart:verify_p2' 'TNM'%}"><img src="{% static 'img/tnm.jpg' %}" class="rounded" width="20">Mpamba</a>
			 	</div>
			 </div>
			 <div class="col-sm-12 col-lg-10">
			 	 <div>
			 	 	<div class="table-responsive" id="verification_table">
			 	 		<table class="table">
			 	 			<thead style="background-color:orange;color:white;">
			 	 				<th>Name</th>
			 	 				<th>Ref number</th>
			 	 				<th>Required</th>
			 	 				<th>Amount</th>
			 	 				<th>Date</th>
			 	 				<th>Verify</th>
			 	 			</thead>
			 	 			{% for payment in payment %}
			 	 			<tr>
			 	 				<td>{{payment.name}}</td>
			 	 				<td>{{payment.rep_no}}</td>
			 	 				<td>{{payment.required}}</td>
			 	 				<td>{{payment.amount}}</td>
			 	 				<td>{{payment.created_at}}</td>
			 	 				<td>
			 	 					<a onclick="verify('{{payment.id}}');" href="javascript:void(0);">V</a>
			 	 				</td>
			 	 			</tr>
			 	 			{% empty%}
			 	 			 <tr >
			 	 			 	<td colspan="5" style="color:red;font-size:30px;">No any payments</td>
			 	 			 </tr>
			 	 			{% endfor %}
			 	 		</table>
			 	 	</div>
			 	 </div>
			 </div>
		</div>
	</div>
</section>

{% endblock %}

cart/templates/cart/mobile_thax.html
{% extends "index/base.html"%}
{% load static %}
{% load crispy_forms_tags %}


    
{% block body %}

{% include 'index/header.html '%}

<section class="my-1">
   <div class="container" id="inner_nav">
      <a href="{% url 'index:index' %}">Home</a>
      <a href="javascript:void(0);">/</a>
      <a href="{% url 'products:mainshop' %}">Products</a>
      <a href="javascript:void(0);">/</a>
      <a href="{% url 'cart:cart_view' %}">cart</a>
      <a href="javascript:void(0);">/</a>
      <a href="#">Paypal</a>
   </div><hr>
</section>



<section class="my-4">
  
   <div class="container p-2 text-center">
      <div class="dashboard_detail_area">
        <div class="row">
            <div class="col-sm-12 col-lg-3">
              
            </div>
            <div class="col-sm-12 col-lg-6">
                 <h1 style="color:orange;"><strong>Thank you!!!</strong></h1><hr>
                 <p>We will deliver your item to you after verifying your payment.Take note that, we have items from different vendors, so if you buy more than one item, We will deliver it to you after collecting all products from our vendors.</p>
                <p>You will get secret code after verifying your payment.you will use this code to collect your products from our agent</p>
                <a class="mt-2 p-2" id="custom_btn" href="{% url 'account:customer_account'%}">View your order</a>  
            </div>
        </div>
      </div>
   </div>
</section>

{% endblock %}

cart/templates/cart/paypal.html
{% extends "index/base.html"%}
{% load static %}
{% load crispy_forms_tags %}


    
{% block body %}

{% include 'index/header.html '%}

<section class="my-1">
   <div class="container" id="inner_nav">
      <a href="{% url 'index:index' %}">Home</a>
      <a href="javascript:void(0);">/</a>
      <a href="{% url 'products:mainshop' %}">Products</a>
      <a href="javascript:void(0);">/</a>
      <a href="{% url 'cart:cart_view' %}">cart</a>
      <a href="javascript:void(0);">/</a>
      <a href="#">Paypal</a>
   </div><hr>
</section>

{% if finish_payment %}<!--error msg-->
<div id="terms_error" class="text-center p-2 mb-4 alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
     </button>
	<p style="color:red;">{{finish_payment}} {{request.user}}</p>
</div>
{% endif %}

<section class="my-2">
	<div class="container">
		<div class="row">

			<div class="col-sm-12 col-lg-6">
				<div class="rounded p-2" style="background-color:rgb(241,246,247);">
					<div class="row">
						<div class="col">
							<p style="color:orange;"><strong>Item</strong></p>
						</div>
						<div class="col">
							<p style="color:orange;"><strong>Price</strong></p>
						</div>
					</div>
					{% for cart in cart.cart.all %}
					<div class="row">
						<div class="col">
							<p>{{cart}}</p>
						</div>
						<div class="col">
							<p>{{cart.get_final_price}}</p>
						</div>
					</div>
					{% endfor %}<hr>
					<div class="row">
						<div class="col">
							<h4 style="color:orange;"><strong>Total(MWK)</strong></h4>
						</div>
						<div class="col">
							<h4 style="color:orange;"><strong>{{cart.get_total}}</strong></h4>
						</div>
					</div>
					<div class="row">
						<div class="col">
							<h4><strong>Total(USD)</strong></h4>
						</div>
						<div class="col">
							<h4><strong>{{USD}}</strong></h4>
						</div>
					</div>
				</div>
			</div>

			<div class="col-sm-12 col-lg-6">
				<div>
				 <h4 style="color:orange;"><strong>NOTE:</strong></h4>
				 <P style="color:red;" >Please remember to click return to <span style="color:green;">Merchant button</span> after completing your payment with paypal</P>
				</div><hr>
				<div class="text-center">
					{{paypal_form.render}}<hr>
					<p><strong>USD {{USD}}</strong></p>
				</div>
				<!--<a href="{% url 'cart:paypal_thax'%}">Click</a>-->
			</div>

		</div>
	</div>
</section>

{% endblock %}