blog/urls.py
from . import views
from django.urls import path

app_name = "blog"

urlpatterns = [
    path('blog/',views.blog,name="blog"),
    path('blog/<cate>/',views.blog,name="blog2"),
    path('blog_detail/<slug>/',views.blog_detail,name="blog_detail"),
    path('addblog/',views.AddBlog,name="AddBlog")
]

cart/urls.py
from . import views
from django.urls import path

app_name = "cart"

urlpatterns = [
    path('cart/',views.shopingcart,name="cart"),
    path('add_to_cart/<slug>/',views.add_to_cart,name="add_to_cart"),
    path('cart_view/',views.cart_view,name="cart_view"),
    path('remove_cart/<int:id>/',views.remove_cart,name="remove_cart"),
    path('billing/<int:id>/',views.billing,name="billing"),
    path('paypal/<int:id>/',views.paypal,name="paypal"),
    path('stripe/<int:id>/',views.stripe,name="stripe"),
    path('charge/',views.charge_d,name="charge"),
    path('paypal_thax/',views.paypal_thax,name="paypal_thax"),
    path('delivered/',views.delivered,name="delivered"),
    path('Payment_verification/',views.confirm_mobile_payments,name="verify_p"),
    path('Payment_verification/<args>/',views.confirm_mobile_payments,name="verify_p2")
]

help/urls.py
from . import views
from django.urls import path

app_name = "help"

urlpatterns = [
    path('help_&_support/',views.help,name="help"),
   ]

index/urls.py
from . import views
from django.urls import path

app_name = "index"

urlpatterns = [
    path('',views.index,name="index"),
    path('contact/',views.contact,name="contact"),
    path('needed_items/',views.place_order_list,name="place_order_list"),
    path('needed_item/<CATE>/',views.place_order_list,name="place_order_list2"),
    path('main_needed_item_view/',views.main_needed_item_view,name='main_needed_item_view'),
    path('edit_needed_item_form/<int:id>/',views.edit_needed_item_form,name="edit_needed_item_form"),
    path('about/',views.about,name="about"),
    path('subscribe/',views.Subscribe,name="Subscribe"),
    path('unsubscribe/',views.unsubscribe,name="unsubscribe"),
    path('terms_conditions/',views.terms_conditions,name="terms_conditions")
]

music/urls.py
#Author Isaac Kakodwa
from . import views
from django.urls import path

app_name = "music"

urlpatterns = [
    path('music/',views.music,name="music"),
    path('music/<args_1>/',views.music,name="music_1"),
    path('main_music/',views.main_music,name="main_music"),
    path('main_music2/<args>/',views.main_music,name="main_music_2"),
    path('music_2/<other_args>/',views.music,name="music_2"),
    path('user_music_list/',views.user_music_list,name='user_music'),
    path('user_music_list2/<args_M>/',views.user_music_list,name='user_music2'),
    path('album_list/<CATEGORY>/',views.album_list,name="album_list"),
    path('album_list2/<TOP_TEN>/',views.album_list,name="album_top_ten"),
    path('album_list_detail/<slug>/',views.album_list_detail,name="album_list_detail"),
    path('album_list_detail2/<slug_2>/',views.album_list_detail,name="album_list_detail2"),
    path('create_album/',views.create_album,name="create_album"),
    path('add_track',views.add_track,name="add_track"),
    path('edit_track/<int:edit_track_id>/',views.add_track,name="edit_track"),
    path('add_track/<slug>/',views.add_track,name="add_track2"),
    path('music_detail/<slug>/',views.music_detail,name="music_detail"),
    path('add_youtube_feed/',views.add_youtube_feed,name="add_youtube_feed"),
    path('youtube_feed_list/',views.youtube_feed_list,name="youtube_feed_list"),
    path('youtube_feed/<CATE>/',views.youtube_feed_list,name="youtube_feed_CATE")
]

mzeebies/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django .conf.urls. static import static
from django .conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls')),
    path('help/',include('help.urls')),
    path('blog/',include('blog.urls')),
    path('products/',include('products.urls')),
    path('music/',include('music.urls')),
    path('account/',include('account.urls')),
    path('cart/',include('cart.urls')),
    path('vendor/',include('vendor.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    #path("stripe/", include("djstripe.urls", namespace="djstripe")),
    path('paypal/', include('paypal.standard.ipn.urls')),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password_reset.html',
             subject_template_name='account/password_reset_subject.txt',
             email_template_name='account/password_reset_email.html',
             # success_url='/login/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]

#handler404 = views.error_404
#handler500 = views.error_500


urlpatterns+=staticfiles_urlpatterns()

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/templates/index/about.html
{% extends "index/base.html"%}
{% load static %}
{% load crispy_forms_tags %}


    
{% block body %}

{% include 'index/header.html '%}

<section class="my-1">
   <div class="container" id="inner_nav">
      <a href="{% url 'index:index' %}">Home</a>
      <a href="javascript:void(0);">/</a>
      <a href="#">About</a>
    
   </div><hr>
</section>

<section>
	<div class="container">
		<div class="">
			<h4><strong>About us</strong></h4><hr>
			<p class="">MzeeBies is the Malawi leading online marketplace for goods made in Malawi and other countries.MzeeBies digital market hosts  wide range of categories including Apparel & Accessories, Computers & Networking, Consumer Electronics, Toys & Hobbies, Health & Beauty, Bags & Jewelry, Home, Auto,Music and more.</p>
		</div>
	</div>
</section>

<section class="my-2">
      <div class="container">
       <h4 class="text-center"><strong>Our Team</strong></h4><hr>
       <div  class="brand_ik">
               {% for agent in agents %}
	  <div class="mx-2">
	  	  <div class="text-center p-2 rounded agent_info">
	  	  	 <img src="{{agent.file.url}}" class="d-block w-100 rounded-circle">
	  	  	 <h4><strong>{{agent}}</strong></h4>
	  	  	 <p>{{agent.title}}</p>
	  	  	 <a id="custom_btn2" href="javascript:void(0);" onclick="agent_detail('{{agent.id}}');">Contact</a>
	  	  	 
	  	  	 <div class="agent_info_detail rounded text-center p-2 " id="agent{{agent.id}}">
	  	  	 {% if request.user.is_superuser %}
	  	  	 <a class="close" href="{% url 'vendor:edit_agent' agent.id %}">Edit</a>
	  	  	 {% endif %}
	  	  	 <h4 style="color:white;"><strong>{{agent}}</strong></h4><hr>
	  	  	 <p>{{agent.district}} / {{agent.area}}</p>
	  	  	 <p style="white-space:nowrap;overflow:hidden;text-overflow: ellipsis; ">{{agent.email}}</p>
	  	  	 <p>{{agent.phone_number}}</p>
	  	  	 <a id="custom_btn" href="javascript:void(0);" onclick="agent_detail_hide('{{agent.id}}');">Hide</a>
	  	  </div>
	  	  </div>
	  	  
	  </div>
	{% empty %}
	    <div class="co-sm-12 col-lg-12">
	    	 <p style="color:red;font-weight:bold;">Currently there is no agent in your area!!</p>
	    </div>
	{% endfor %}
        </div>
   </div>
</section>

{% endblock %}

index/templates/index/base.html
{% load static from staticfiles %}
{% load static %}


<!DOCTYPE html>
<html>
<head>
   {% include 'index/top_static.html '%}
</head>

<body>


<div class="text-center alert"  id="main_alert">
    <div class="rounded" id="inner_main_alert">
       <div class="rounded-top p-1" style="background-color:orange">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
       </button>
          <p style="font-weight:bold;color:white;" id="inner_main_alert_hd"><strong></strong></p>
          
       </div>
       <div class="p-4">
           <p id="inner_main_alert_text">
  
          </p>
       </div>
    </div>
</div>


<div class=""  id="place_order_popup">
    <div class="rounded" id="inner_place_order_popup">
       <div class="rounded-top p-2 text-center" style="background-color:orange;">
          <a href="javascript:void(0);" class="close" onmouseover="display_place_order_form();">x</a>
            <h4 style="font-weight:bold;color:red;" id="inner_main_alert_hd"><strong></strong>Place your order here</h4>
       </div>
       
        <div class="p-4" id="place_order_feedback_area">
            <form action="{% url 'index:about' %}" method="GET" class="form-group" id="place_order_form_nt">
                       {% csrf_token %}
                <label class="text-left">Full name</label>
                <input required="true" class="form-control" type="text" name="name">
                <label>Location(District and area)</label>
                <input required="true" class="form-control"  type="text" name="location">
                <label>Whatsapp number</label>
                <input required="true" class="form-control"  type="number" name="phone">

                <label>Category</label>
                <select required="true" class="form-control"  type="text" name="category">

                  {% for option in options %}
                      <option value="{{option}}">{{option}}</option>
                  {% endfor %}
                    
                </select>

                <label>Name products you want(Specify)</label>
                <textarea required="true" class="form-control"  type="text" name="item"></textarea>
                <label>Your budget</label>
                <input required="true" class="form-control"  type="number" name="budget">
                <button class="mt-2" style="border:none;" id="custom_btn">Place order</button>
             </form>
        </div>

    </div>
</div>

<div class="p-2 " id="nav_menu" style="position:fixed;">
       <button style="color:white;" onclick="hidenav();" type="button" class="close">
        <span aria-hidden="true">×</span>
     </button>
    <div style="background-color:#222222;">
       <a href="{% url 'index:index' %}">
        <img src="{% static 'img/logo.png' %}" width="150">
    </a>
    </div>
   <div>
      <a href="{% url 'index:index'%}">Home</a>
      <a href="{% url 'products:mainshop'%}">Shop</a>
      <a href="{% url 'blog:blog'%}">Blog</a>
      <a href="{% url 'music:music'%}">Music</a>
      <a href="{% url 'index:place_order_list' %}">Needed item/s</a>
      <a href="{% url 'index:about'%}">About</a>
      <a href="{% url 'index:contact'%}">Contacts</a>
      <a href="{% url 'cart:cart_view' %}">Your cart ( {{cart_count}} )
      </a>
      {% if user.is_authenticated  %}
            {% if user.is_superuser  %}
                    <hr>
                    <a href="{% url 'account:dashboard'%}"></i>My account</a>
                    <a href="{% url 'account:dashboard'%}">Orders</a>
                    <a href="{% url 'account:Dashboard2' 'delivered'%}">
                     Derevered orders</a><hr>
                    <a href="{% url 'vendor:bill_verification'%}">Vendor bills</a>
                    <a href="{% url 'cart:verify_p'%}">Mobile payments</a><hr>
                    <a href="{% url 'products:category_v' %}">Add Categories</a>
                    <a href="{% url 'products:upload_brand' %}">Add products brand</a>
                    <a href="{% url 'music:add_youtube_feed'%}">Add youtube video</a>
                    <a href="{% url 'vendor:vendor_db' %}">Vendor db</a>
                    <a href="{% url 'index:main_needed_item_view'%}">Needed items</a>
                    <a href="{% url 'vendor:agent' %}">Add agent</a><hr>
                    <a href="/admin/">Admin</a>
                {% else %}
                    <hr>
                    <a href="{% url 'account:customer_account'%}">My account</a>
                    <a href="{% url 'account:customer_account'%}">Complete orders</a>
                    <a href="{% url 'account:customer_account2' 'Delivered' %}">Delivered</a><hr>
                {% endif %}

                    {% if vendor_account %}
                        <a href="{% url 'vendor:vendor_account'%}">Vendor account</a>

                        {% if categories %}

                          {% if user_bill.due_date %}
                             <a href="{% url 'products:additem_msg'%}">Add product</a>
                          {% else %}
                              <a href="{% url 'account:bill'%}">Add product</a>
                          {% endif %}

                        {% endif %}

                        {% if user_bill.due_date != None %}
                          <a href="{% url 'blog:AddBlog' %}">Add Blog</a>
                        {% else %}
                          <a href="{% url 'account:bill'%}">Add Blog</a>
                        {% endif %}
                          <a href="{% url 'account:bill'%}">Pay bills</a>
                    {% else %}
                          <a href="{% url 'vendor:vendor'%}">Become our Vendor</a><hr>
                    {% endif %}
                   <a href="{% url 'account:logout_view'%}">Logout</a>
        {% else %}
            <a href="{% url 'account:google_login'%}"><i class="fa fa-user" aria-hidden="true"></i>Login</a>
        {% endif %}
   </div>
</div>

<a id="scroll_up_btn" href="javascript:void(0);">
  <img src="{% static 'img/up_arrow.png'%}" height="64">
</a>



<div style="position:fixed;bottom:200px;left:10px;z-index:3;">
    <a id="custome_btn" href="javascript:void(0);" onmouseover="display_place_order_form();">
       <img id="order_btn_img" onmouseout="place_order2();" onmouseover="place_order();" src="{% static 'img/order_btn.png' %}" height="64">
    </a>
</div>


<div id="diisplay_popup_advert_ajax">
    <!--Advert and place orders popup here--->
</div>


{% if added_sucessfuly_msg %}
<div id="outer_complete_msg">
   <div id="complete_msg" class="alert">
    <button type="button" class="close"  onclick="hide_alert();">
        <span aria-hidden="true">×</span>
     </button>
     <p><strong style="color:green;">SUCCESS</strong></p>
     <hr>
    <p class="p-2 rounded" style="color:orange;"><strong>{{added_sucessfuly_msg}}</strong></p>
</div>
</div>
{% endif %}


{% block body %}

{% endblock %}

{% include 'index/subscripbe.html' %}
{% include 'index/footer.html' %}

{% include 'index/bottom_static.html '%}


<!--<div class="a2a_kit a2a_kit_size_32 a2a_floating_style a2a_vertical_style" style="right:0px; top:100px;">
    <a class="a2a_button_facebook"></a>
    <a class="a2a_button_twitter"></a>
    <a class="a2a_button_pinterest"></a>
    <a class="a2a_dd" href="https://www.addtoany.com/share"></a>
</div>-->

<div class="a2a_kit a2a_kit_size_32 a2a_floating_style a2a_default_style" style="bottom:20px; left:7%; transform:translateX(-50%);">
    <a class="a2a_button_facebook"></a>
    <a class="a2a_button_twitter"></a>
    <a class="a2a_button_pinterest"></a>
    <a class="a2a_dd" href="https://www.addtoany.com/share"></a>
</div>

<!--<script>
var a2a_config = a2a_config || {};
a2a_config.overlays = a2a_config.overlays || [];
a2a_config.overlays.push({
    services: ['pinterest', 'facebook', 'houzz', 'tumblr'],
    size: '50',
    style: 'horizontal',
    position: 'top center'
});
</script>-->

<script async src="https://static.addtoany.com/menu/page.js"></script>

<script type="text/javascript">




</script>

</body>
</html>

index/templates/index/carousel.html
{% load static %}
<div class="container" id="ik_header_contacts">

	 <div id="header_contacts">
	 	<a class="mr-4" href=""><i class="fa fa-phone mr-2" aria-hidden="true"></i>+(265) 99 33 444 16</a>
	 	<a href=""><i class="fa fa-envelope mr-2" aria-hidden="true"></i>ikpixels.py@gmail.com</a>

	 	{% if user.is_authenticated  %}
	 	        {% if user.is_superuser  %}
                    <div style="float:right;" class="logout_menu">
                    	<a  href="javascript:void(0);"><i class="fa fa-user mr-2" aria-hidden="true"></i>{{request.user}}</a>
                    	<div class="logout_content p-2 rounded-bottom">
                    		<a href="{% url 'account:dashboard'%}">Dashboard</a>
                    		<a href="{% url 'account:logout_view'%}">
                    			<strong>Logout</strong>
                    		</a>
                    	</div>
                    </div>
                {% else %}
                    <div style="float:right;" class="logout_menu">
                    	<a href="javascript:void(0);"><i class="fa fa-user mr-2" aria-hidden="true"></i>{{request.user}}</a>
                    	<div class="logout_content p-2 rounded-bottom">
                    		<a href="{% url 'account:customer_account'%}">Account</a>
                    		<a href="{% url 'account:logout_view'%}">
                    			<strong>Logout</strong>
                    		</a>
                    	</div>
                    </div>
                {% endif %}
        {% else %}
            <a style="float:right;" href="{% url 'account:google_login'%}"><i class="fa fa-user mr-2" aria-hidden="true"></i>Login</a>
        {% endif %}

	 	<a style="float:right;color:red;" href="{% url 'cart:cart_view' %}"><strong><i class="fa fa-shopping-cart mr-2" aria-hidden="true">Your Cart({{cart_count}})</i></strong></a>
	 </div>

	 <div class="row">
	 	 <div class="col-sm-12 mt-2 p-2 rounded " id="shop_menu">
	 	 	<a href="{% url 'index:index' %}">
	 	 		<img src="{% static 'img/logo.png' %}" width="150">
	 	 	</a>
	 	 	<div style="float:right;" class="menu_bar">
	 	 		<a href="javascript:void(0);" onclick="displaynav();">
	 	 			<img src="{% static 'img/ikmenu.png' %}" width="60">
	 	 		</a>
	 	 	</div>
	 	 	<a id="search_btn" class="mr-3" style="float:right;color:white;" href="javascript:void(0);">
	 	 		<i class="fa fa-search" aria-hidden="true"></i>
	 	 	</a>
	 	 	
	 	 	
	 	 </div>

	 	 <div class="col-sm-12 p-2 rounded-bottom" id="search_menu">
	 	 	    <form method="GET">
                    <input type="search"placeholder="{{search_placeholder}}" aria-label="Search" name="q">
                </form>
	 	 </div>

	 	 <div class="col-sm-12 col-lg-6">
	 	 	 <div class="text-center animatedParent" id="Welocome_msg">
	 	 	 	<h1 class='animated rotateIn'><strong>Welcome to <span style="color:orange;">MzeeBies</span></strong></h1>
	 	 	 	<p class='animated fadeInLeft' style="color:white;"><strong>Shop is fun</strong></p>
	 	 	 	<h4 class='animated fadeInRight'><strong>Browse Our Premium Products</strong></h4>
	 	 	 	<div class="mt-4 p-4 animated flipInX">
	 	 	 		<a href="{% url 'products:mainshop' %}" class="p-3 rounded animated flip" id="custom_btn">Browse Now</a>
	 	 	 	</div>
	 	 	 </div>
	 	 </div>

	 	 <div class="col-sm-12 col-lg-6 ">
	 	 	    <div class="multiple-items" id="home_img">
                     {% for timer in popular %}
                     {% if timer.file %}
                     <div class="rounded p-2 mb-2">
                        <a href="{% url 'products:detail' timer.slug %}">
                        	 <img src="{{timer.file.url}}" class="img-fluid rounded">
                        </a>
                     </div>
                     {% endif %}
                     {% endfor %}
                </div>
	 	 </div>
	 </div>
</div>

index/templates/index/contact.html
{% extends "index/base.html"%}
{% load static %}
{% load crispy_forms_tags %}


    
{% block body %}

{% include 'index/header.html '%}

<section class="my-1">
   <div class="container" id="inner_nav">
      <a href="{% url 'index:index' %}">Home</a>
      <a href="javascript:void(0);">/</a>
      <a href="">Contact</a>   
   </div><hr>
</section>



<section>
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-lg-6">
				<div class="p-4 rounded mb-2" style="background-color:rgb(241,246,247);">
					<h4>Contact Information</h4><hr>
					<p><strong><i class="fa fa-phone mr-2" aria-hidden="true"></i>+(265) 99 33 444 16</strong></p>
					<p><strong><i class="fa fa-envelope mr-2" aria-hidden="true"></i>ikpixels.py@agmail.com</strong></p>
					<p><strong><i class="fa fa-map-marker mr-2" aria-hidden="true"></i>Lilongwe/Malawi</strong></p>
					<p><strong><i class="fa fa-globe mr-2" aria-hidden="true"></i>www.ikpixels.com</strong></p>
				</div>
			</div>
			<div class="col-sm-12 col-lg-6">
				<div class="p-4 rounded" style="background-color:rgb(241,246,247);">
					<h4>Get In Touch</h4><hr>
					<form><!--pass---></form>
					<form id="contact_form" action="{% url 'index:contact' %}">{% csrf_token %}
						<div class="row">
							 <div class="col">
							 	<label><strong>First name</strong></label>
							 	<input required="true" class="form-control" type="text" name="first_name">
							 </div>
							 <div class="col">
							 	<label><strong>Last name</strong></label>
							 	<input required="true" class="form-control" type="text" name="last_name">
							 </div>
						</div>
						<div class="row">
							 <div class="col">
							 	<label><strong>Phone</strong></label>
							 	<input required="true" class="form-control" type="number" name="phone">
							 </div>
							 <div class="col">
							 	<label><strong>Email</strong></label>
							 	<input class="form-control" type="email" name="email" required="true" placeholder="example@gmail.com">
							 </div>
							 
						</div>
						<div class="mt-2">
							<label>
								<strong>Message</strong>
							</label>
							<textarea name="msg" required="true" class="form-control"></textarea>
						</div>
						<p id="success_c" style="color:green;display:none;"><strong>Message sent successfuly</strong></p>
						<p id="contact_error" style="color:red;display:none;"><strong>Something is wrong</strong></p>
						<div class="mt-2">
							<button style="width:100%;border:none;" id="custom_btn">Send message</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="mt-4 p-2" style="background-color:rgb(241,246,247);">
	<div class="container">
		<iframe  src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d7708.193737669421!2d34.964107!3d-14.987326999999999!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x30e35e2026db8b1!2sBalaka%20Secondary%20School!5e0!3m2!1sen!2smw!4v1577051871066!5m2!1sen!2smw" width="100%" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
	</div>
</section>


{% endblock %}

index/templates/index/error.html
{% load static %}

<div class="text-center mt-4" style="padding-top:100px;padding-bottom:200px;">
	<h1 style="color:red;"><strong>404</strong></h1>
   <p><strong>Error - Not Found</strong></p>
   <p>Sorrey We’re not able to find what you looking for</p>
</div>

index/templates/index/footer.html
{% load static %}
<section class="mt-0 py-4"  id="footer" style="background:url({% static 'img/footer-bg.png'%});background-repeat:no-repeat;background-position: center center;background-size: cover;">
	<div class="container">
		 <div class="row">
		 	 <div class="col-sm-12 col-lg-5">
		 	 	 <a href="{% url 'index:index'%}">
		 	 	 	<img src="{% static 'img/logo.png' %}" width="150">
		 	 	 </a>
		 	 	 <p class="text-justify mt-2">MzeeBies is the Malawi leading online market place for goods made in Malawi and other countries.MzeeBies digital market hosts  wide range of categories including Apparel & Accessories, Computers & Networking, Consumer Electronics, Toys & Hobbies, Health & Beauty, Bags & Jewelry, Home, Auto,Music and more. </p>
		 	 </div>

		 	 <div class="col-sm-12 col-lg-3">
		 	 	 <h4 style="color:orange;">Quick search</h4>
		 	 	 <a href="{% url 'index:index'%}">Home</a>
		 	 	 <a href="{% url 'products:mainshop'%}">Shop</a>
		 	 	 <a href="{% url 'music:music'%}">Music</a>
		 	 	 <a href="{% url 'music:youtube_feed_list'%}">Videos</a>
		 	 	 <a href="{% url 'blog:blog'%}">Blog</a>
		 	 	 <a href="{% url 'index:place_order_list' %}">Needed item/s</a>
		 	 	 <a href="{% url 'index:about'%}">About</a>
		 	 	 <a href="{% url 'index:contact'%}">Contacts</a>
		 	 	 <a href="{% url 'index:terms_conditions'%}">Terms and Conditions</a>
		 	 	 <a href="{% url 'help:help'%}">Help & Support</a>
		 	 	 <a href="{% url 'account:google_login'%}">Login</a>
		 	 	 <a href="{% url 'account:register_view'%}">Register</a>

		 	 	 {% if user.is_authenticated %}
		 	 	    <a href="{% url 'account:change_password'%}">Change password</a>
		 	 	 {% endif %}
		 	 </div>

		 	 <div class="col-sm-12 col-lg-4">
		 	 	 <h4 style="color:orange;" >Get in touch </h4>
		 	 	 <a href="#"><i class="fa fa-phone mr-2" aria-hidden="true"></i>+(265) 99 33 444 16</a>
		 	 	 <a href="#"><i class="fa fa-envelope mr-2" aria-hidden="true"></i>ikpixels.py@gmail.com</a>
		 	 	 <a href="https://web.facebook.com/IKpixels/"><i class="fa fa-facebook-square mr-2" aria-hidden="true"></i>facebookpage</a>

		 	 	 {% if vendor_account %}
                        <a class="p-2 rounded text-center mt-4" style="border:2px solid orange;" href="{% url 'vendor:vendor_account'%}"><strong>Your vendor account</strong></a>
                    {% else %}
                        <a class="p-2 rounded text-center mt-4" style="border:2px solid orange;" href="{% url 'vendor:vendor'%}"><strong>Become our Vendor</strong></a>
                    {% endif %}
		 	 	
		 	 </div>

		 	 <div class="col-sm-12 col-lg-12">
		 	 	<hr>
		 	 	<p style="color:white;">Payment accepted</p>
		 	 	<div class="" id="payment_methods_icon">
		 	 		<a class="mr-2" href="https://airtel.mw/airtelmoney/faq">
		 	 				<img src="{% static 'img/airtel.jpg' %}" class="rounded" height="25">
		 	 	    </a>
		 	 	    <a class="mr-2" href="https://www.tnm.co.mw/ui/tnm-october/index.php/mpamba">
		 	 				<img src="{% static 'img/tnm.jpg' %}" class="rounded" height="25">
		 	 		</a>
		 	 		<a href="https://www.paypal.com/mw/webapps/mpp/merchant">
		 	 				<img src="{% static 'img/paypal.jpg' %}" class="rounded" height="25">
		 	 		</a>
		 	 	</div>
		 	 	
		 	 </div>

		 </div>
		 <div class="text-center">
		 	<hr>
            <a href="http://www.ikpixels.com/">
            	<img height="30" src="{% static 'img/ik.png'%}">
            </a>
		 	<p><a href="http://www.ikpixels.com/"> Powered by IKpixels</a> Copyright &copy;<script>document.write(new Date().getFullYear());</script>, All rights reserved</p>
		 			 </div>
	</div>
</section>

index/templates/index/place_order_feedback.html
<div>
	<h4>Thank you for taking order here!!</h4>
	<p>We will come back to you soon</p>
</div>

index/templates/index/subscribe_msg.html
<p>{{msg}}</p>