account/urls.py
from . import views
from django.urls import path

app_name = "account"

urlpatterns = [
    path('dashboard/',views.Dashboard,name="dashboard"),
    path('dashboard/<args>/',views.Dashboard,name="Dashboard2"),
    path('login/',views.login_view,name="google_login"),
    path('bill/',views.bill,name="bill"),
    path('change_password/',views.change_password,name="change_password"),
    path('register/',views.register_view,name="register_view"),
    path('logout/',views.logout_view,name="logout_view"),
    path('cart_detail/',views.cart_detail,name="cart_detail"),
    path('my_account/',views.customer_account,name="customer_account"),
    path('my_account/<args>/',views.customer_account,name="customer_account2")
]

blog/urls.py
from . import views
from django.urls import path

app_name = "blog"

urlpatterns = [
    path('blog/',views.blog,name="blog"),
    path('blog/<cate>/',views.blog,name="blog2"),
    path('blog_detail/<slug>/',views.blog_detail,name="blog_detail"),
    path('addblog/',views.AddBlog,name="AddBlog")
]

index/urls.py
from . import views
from django.urls import path

app_name = "index"

urlpatterns = [
    path('',views.index,name="index"),
    path('contact/',views.contact,name="contact"),
    path('needed_items/',views.place_order_list,name="place_order_list"),
    path('needed_item/<CATE>/',views.place_order_list,name="place_order_list2"),
    path('main_needed_item_view/',views.main_needed_item_view,name='main_needed_item_view'),
    path('edit_needed_item_form/<int:id>/',views.edit_needed_item_form,name="edit_needed_item_form"),
    path('about/',views.about,name="about"),
    path('subscribe/',views.Subscribe,name="Subscribe"),
    path('unsubscribe/',views.unsubscribe,name="unsubscribe"),
    path('terms_conditions/',views.terms_conditions,name="terms_conditions")
]

mzeebies/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django .conf.urls. static import static
from django .conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls')),
    path('help/',include('help.urls')),
    path('blog/',include('blog.urls')),
    path('products/',include('products.urls')),
    path('music/',include('music.urls')),
    path('account/',include('account.urls')),
    path('cart/',include('cart.urls')),
    path('vendor/',include('vendor.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    #path("stripe/", include("djstripe.urls", namespace="djstripe")),
    path('paypal/', include('paypal.standard.ipn.urls')),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password_reset.html',
             subject_template_name='account/password_reset_subject.txt',
             email_template_name='account/password_reset_email.html',
             # success_url='/login/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]

#handler404 = views.error_404
#handler500 = views.error_500


urlpatterns+=staticfiles_urlpatterns()

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from . import views
from django.urls import path

app_name = "products"

urlpatterns = [
    path('shop/',views.mainshop,name="mainshop"),#for main shop
    path('shop/<args_>/',views.mainshop,name="mainshop2"),# for categories
    path('mainshop22/<args_2>/',views.mainshop,name="type"),
    path('deals_payment_form/<slug>/',views.Deal_payment_form,name="deal_payment_form"),
    path('additem/<int:id>/',views.additem,name="additem"),
    path('additem_msg/',views.additem_msg,name="additem_msg"),
    path('Edit/<slug>/',views.additem,name="edit"),
    path('item_view/',views.item_view,name="item_view"),
    path('additemBanner/',views.additemBanner,name="banner"),
    path('additemBanner/<int:args>/',views.additemBanner,name="banner_edit"),
    path('detail/<slug>/',views.detail,name="detail"),
    path('additemImage/<slug>/',views.additemImage,name="additemImage"),
    path('category_v/',views.category_v,name="category_v"),
    path('upload_brand/',views.upload_brand_img,name="upload_brand"),
    path('timer/',views.timer,name="timer"),
    path('delete/<slug>/',views.delete_item,name="delete_item"),
    path('delete/<int:id>/',views.delete_brand,name="delete_brand"),
    path('remove_category/',views.remove_category,name="remove_category")

]

products/views.py
from django.shortcuts import render,redirect
from . forms import ProductForm,EditProductForm,deals_form,BrandForm,ItemBanner,AddImageForm,category_form
from . models import product,Popular,Categories,category_banner,Brand,item_contacts
from django.http import HttpResponse,JsonResponse,HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from cart.models import OrderItem
from index.snipt import cart_count,send_html_mail,vendor_account,added_sucessfully_msg,popups_advert
from vendor.models import vendor,BillPlan,vendor_bill_plan,agent_info
from vendor.forms import deal_payment_form


def user_location(context,request):#with vendor account
	if request.user.is_authenticated and not request.user.is_anonymous:

		try:
			area = vendor.objects.get(user=request.user)
			context['district'] = area.district
			context['area'] = area.area

		except vendor.DoesNotExist:
			pass

def main_shop(request,context,args_=None,args_2=None):
	context['categories'] = Categories.objects.all()


	if request.session.has_key('added_sucessfuly_msg'):
		context['added_sucessfuly_msg'] = request.session['added_sucessfuly_msg']
		del request.session['added_sucessfuly_msg']

	cart_count(request.user,context)
	vendor_account(context,request)
	user_location(context,request)#with vendor account
	
	context['brand'] = Brand.objects.all()

	if request.session.has_key('user_error'):#for anonymous user
		user_error = request.session['user_error']
		context['user_error'] = user_error
		del request.session['user_error']

	if args_:
		item = product.objects.filter(Q(brand2=args_)|
			                          Q(vendor=args_)|
			                          Q(area=args_)|
			                          Q(district=args_)|
			                          Q(category2=args_)).distinct().order_by('-updated_at')
		context['title'] = args_
		context['args'] = args_

	elif args_2 == 'Top_Seller':
		context['args'] = "Top Seller"
		context['title'] = "Top Seller"
		item = product.objects.all().order_by('-topSeller')

	elif args_2 == 'Item_Deals':
		deals_count = product.objects.filter(timer__isnull=False).count()
		context['args'] = "Deals" 
		context['title'] = "Deals"
		context['deals'] = "Display deals countdown"
		item = product.objects.filter(timer__isnull=False).order_by('-updated_at')

	elif args_2 == 'Top_rated':
		context['args'] = "Top Rated"
		context['title'] = "Top Rated"
		item = product.objects.filter(ratings__isnull=False).order_by('-ratings__average')

	elif args_2 == "Popular":
		context['title'] = "Popular"
		context['args'] = "Popular"
		item = product.objects.all().order_by('-view')

	else:
		context['title'] = "Products"
		context['args'] = "All"
		item = product.objects.all().order_by('-updated_at')

	query =request.GET.get('q')

	context['search_placeholder'] = "Search product based on name/your district/your area/Category/vendor/brand"
	if request.session.has_key('q'):
		quer = request.session['q']
		context['args'] = quer
		context['title'] = quer 
		item = item.filter(Q(item__icontains=quer)|
		                   Q(area__icontains=quer)|
		                   Q(vendor__icontains=quer)|
		                   Q(brand2__icontains=quer)|
		                   Q(district__icontains=quer)| 
			               Q(category2__icontains=quer)).distinct()
		del request.session['q']

	if query:
		context['args'] = query
		context['title'] = query
		item =item.filter(Q(item__icontains=query)|
		                  Q(area__icontains=query)|
		                  Q(vendor__icontains=query)|
		                  Q(brand2__icontains=query)|
		                  Q(district__icontains=query)|  
			              Q(category2__icontains=query)).distinct()


	page = request.GET.get('page', 1)
	paginator = Paginator(item,20)

	try:
		item = paginator.page(page)
	except PageNotAnInteger:
		item = paginator.page(1)
	except EmptyPage:
		item = paginator.page(paginator.num_pages)

	context['items']  = item

def mainshop(request,args_=None,args_2=None):
	context = {}
	main_shop(request,context,args_,args_2)
	vendor_account(context,request)

	if request.is_ajax() and request.GET.get('pops'):#Popups/needed items ajax
		popups_advert(request,context)
		html = render_to_string('index/selected_place_order.html',context,request=request)
		return JsonResponse({'data':html})

	return render(request,'products/shop.html',context)

@login_required(login_url="account:google_login")
def Deal_payment_form(request,slug):

	context = {}
	context['title'] = "Make deal"
	context['deal_price'] = vendor_bill_plan.objects.all().last()

	item = product.objects.get(slug=slug)
	context['item'] = item

	if request.method == "POST":

		form = deal_payment_form(request.POST)

		if form.is_valid():
			instance = form.save()
			instance.user = request.user
			instance.item_id  = item.id
			instance.save()

			request.session['added_sucessfuly_msg'] = "You have successfuly made a deal.Your payment will be verified soon!!"

			return HttpResponseRedirect(reverse('products:detail', args=[item.slug]))
	else:
		form = deal_payment_form()

	context['form'] = form
	return render(request,'products/deals_payment_form.html',context)

@login_required(login_url="account:google_login")
def additem(request,id,slug=None):

	context = {}

	context['title'] = "Add product"
	cart_count(request.user,context)
	vendor_account(context,request)

	if slug:
		USER = request.user
		location = vendor.objects.get(user=request.user)
	else:
		USER = vendor.objects.get(id=id).user
		location = vendor.objects.get(id=id)
		
	

	if slug:
		item = product.objects.get(slug=slug)

	try:
		Vendor = vendor.objects.get(user=USER)#getting Vendor full name
	except vendor.DoesNotExist:
		pass

	try:#for allowing user to add item if they  settle their bills
	    Paid_bill   = BillPlan.objects.get(user=USER)
	    context['bill'] = Paid_bill

	    Num_of_item = Paid_bill.item_num
	    added_item  = Paid_bill.item_num2

	    if added_item < Num_of_item or Paid_bill.due_date != None:

	    	if request.method =="POST":
	    		if slug:# for  editing item
	    			form = EditProductForm(request.POST,request.FILES,instance=item) 
	    		else: # for new item entry
	    			form = ProductForm(request.POST,request.FILES)
	    			
	    		if form.is_valid():
	    			instance = form.save()
	    			instance.user = USER
	    			instance.vendor = str(Vendor.fullName)
	    			instance.district = location.district
	    			instance.area = location.area
	    			instance.Paid = True
	    			instance.save()

	    			Paid_bill.item_num2 += 1
	    			Paid_bill.save()

	    			request.session['added_sucessfuly_msg'] = "Item added successfuly"

	    			return redirect('products:item_view')
	    	else:
	    		form = ProductForm()

	    else:
	    	request.session['bill_expired'] = "Your items rich maxmum!!"
	    	return redirect('account:bill')

	except BillPlan.DoesNotExist:
		return redirect('account:bill')

	context['form'] = form

	return render(request,'index/form.html',context)

@login_required(login_url="account:google_login")
def additem_msg(request):
	context = {}
	context['contacts_info'] = item_contacts.objects.all().last()
	context['agents'] = agent_info.objects.all()
	return render(request,'products/additem_msg.html.html',context)

@login_required(login_url="account:google_login")
def item_view(request):
	context = {}
	context['title'] = "Add addition image"
	cart_count(request.user,context)
	vendor_account(context,request)

	query =request.GET.get('q')
	context['search_placeholder'] = "Search product based on name/your district/your area/Category/vendor/brand"
	if query:
		request.session['q'] = query
		return redirect("products:mainshop")

	context['item']  = product.objects.all().last()
	return render(request,'products/item_view.html',context)

def detail(request,slug):
	context = {}

	context['brand'] = Brand.objects.all()
	context['categories'] = Categories.objects.all()

	if request.session.has_key('added_sucessfuly_msg'):
		context['added_sucessfuly_msg'] = request.session['added_sucessfuly_msg']
		del request.session['added_sucessfuly_msg']

	cart_count(request.user,context)
	vendor_account(context,request)
	user_location(context,request)#with vendor account
	
	query =request.GET.get('q')
	context['search_placeholder'] = "Search product based on name/your district/your area/Category/vendor/brand"
	if query:
		request.session['q'] = query
		return redirect("products:mainshop")

	item = product.objects.get(slug=slug)

	related = product.objects.filter(Q(item=item)| 
			                         Q(category=item.category)).distinct() 
	context['related'] = related
	context['r_count'] = related.count()

	context['vendor'] = vendor.objects.get(user=item.user)#getting vendor icon
	
	context['title'] =  item
	context['item'] = item

	popular = Popular(product=item)
	popular.save()

	if request.is_ajax() and request.GET.get('pops'):#Popups/needed items ajax
		popups_advert(request,context)
		html = render_to_string('index/selected_place_order.html',context,request=request)
		return JsonResponse({'data':html})

	return render(request,'products/detail.html',context)

def delete_item(request,slug):
	context = {}
	if request.is_ajax():

		item = product.objects.get(slug=slug)
		item.delete()

		main_shop(request,context)

		html = render_to_string('products/shop2.html',context,request=request)
		return JsonResponse({'data':html})
		


@login_required(login_url="account:google_login")
def additemBanner(request,args=None):
	context = {}

	cart_count(request.user,context)
	vendor_account(context,request)

	if args:
		data = category_banner.objects.get(id=args)
		context['title'] = "Edit banner"
	else:
		context['title'] = "Add category banner"

	if request.method =="POST":

		if args:
			form = ItemBanner(request.POST,request.FILES,instance=data)
		else:

products/templates/products/category.html
{% extends "index/base.html"%}
{% load static %}

{% block body %}
{% include 'index/header.html '%}

<section class="my-1">
	 <div class="container" id="inner_nav">
	 	  <a href="{% url 'index:index' %}">Home</a>
	 	  <a href="javascript:void(0);">/</a>
	 	  <a href="{% url 'account:dashboard' %}">Myaccount</a>
	 	  <a href="javascript:void(0);">/</a>
	 	  <a href="#">Add category</a>
	 </div><hr>
</section>


<section class="my-2">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-lg-6 p-2 my-1 rounded" 
			     style="border:1px solid black;">
				<div id="inner_category">
					<h4>Products categories</h4><hr>
					<ul>
						{% for category in categories %}
						  <li>{{category}} <a onclick="remove_category('{{category.id}}')" href="javascript:void(0);">
						  	<i class="fas fa-trash"></i>
						  </a></li>
						{% empty%}
						  <li>There is no category in your shop</li>
						{% endfor %}
					</ul>
				</div>
				<div>
					<form><!--pass---></form>
					<form id="add_category"  class="form"
					      action="{% url 'products:category_v'%}">
					      {% csrf_token %}
						  <input class="form-control" type="text" name="category">
						  <button style="width:100%; border:none;" class="my-2 p-2" id="custom_btn">Add category</button>
					</form>
				</div>
			</div>
			<div class="col-sm-12 col-lg-6">
				{% if categories %}
				<div class="text-center p-2 rounded my-1" style="border:1px solid black">
					<h4>Available banner (Max = 3 images)</h4><hr>
					<div class="row my-4">
						{% for banner in banner %}
						  <div class="col-sm-12 col-lg-4">
						  	 <div class="my-1">
						  	 	<img src="{{banner.image.url}}" class="img-fluid rounded">
						  	 	<p>{{banner.category}}</p>
						  	 	<a href="{% url 'products:banner_edit' banner.id %}">
						  	 		<i class="fas fa-edit"></i>
						  	 	</a>
						  	 </div>
						  </div>
						{% endfor %}
					</div>
					
					      {% if banner.count < 3 %}
					          <a id="custom_btn" class="p-2 my-4" href="{% url 'products:banner' %}">Add category banner</a>
					      {% endif %}
					
				</div>
                {% endif %}
				<div class="text-center p-2">
					<h4>Available products</h4>
					<h4><strong>{{count}}</strong></h4>
				</div>
			</div>
		</div>
	</div>
</section>



{% endblock %}

products/templates/products/item_view.html
{% extends "index/base.html"%}
{% load static %}

{% block body %}
{% include 'index/header.html '%}

<section class="my-1">
	 <div class="container" id="inner_nav">
	 	  <a href="{% url 'index:index' %}">Home</a>
	 	  <a href="javascript:void(0);">/</a>
	 	  <a href="{% url 'account:dashboard' %}">Myaccount</a>
	 	  <a href="javascript:void(0);">/</a>
	 	  <a href="#">Add image</a>
	 </div><hr>
</section>


<section class="my-4">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-lg-4">
				<div>
					<h4>Main image</h4>
					<img src="{{item.file.url}}" class="img-fluid rounded">
					<p><strong>{{item}}</strong></p>
				</div>
			</div>
			<div class="col-sm-12 col-lg-8">
				<div>
					{% if item.image.all %}
					<h4>Other images(Max = 5 images)</h4>
					{% endif %}
				</div>
				<div class="row p-2 my-3 rounded" style="border:1px solid black">
					{% for item in item.image.all %}
					   <div class="col-sm-12 col-lg-3">
					   	  <div class="my-2">
					   	  	{% if item.file %}
                                <img src="{{item.file.url}}" class="d-block w-100 rounded-top">
                            {% else %}
                                <img src="{% static 'img/item.png '%}" class="d-block w-100 rounded-top">
                            {% endif %}
					   	  </div>
					   </div>
					{% empty %}
					    <p style="color:red;">Empty | Add more images for this {{item}} </p>
					{% endfor %}
				</div>
				<div class="text-center">
					{% if item.image.all.count < 4 %}
					<a class="p-2" id="custom_btn" href="{% url 'products:additemImage' item.slug %}">Add image</a>
					<a class="p-2" id="custom_btn2" href="{% url 'products:mainshop'%}">Go to shop</a>
					{% else %}
					   <p class="my-2" style="color:red;"><strong>Maximum reached !!</strong></p>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

products/templates/products/shop.html
{% extends "index/base.html"%}
{% load static %}
{% load crispy_forms_tags %}


    
{% block body %}

{% include 'index/header.html '%}


<section class="my-1">
   <div class="container" id="inner_nav">
      <a href="{% url 'index:index' %}">Home</a>
      <a href="javascript:void(0);">/</a>
      <a href="{% url 'products:mainshop'%}">{{args}}</a>

      <div style="float:right;">
         <a id="display_category" 
            onclick="display_category();" 
            href="javascript:void(0);">
              <img src="{% static 'img/cat.png' %}" height="20">
          </a>
          <a id="hide_category" 
             href="javascript:void(0);" 
             onclick="hide_category();">
              <img src="{% static 'img/cat2.png' %}" height="20">
           </a>
      </div>
   </div><hr>
</section>

{% if user_error %}
<div id="terms_error" class="text-center p-2 my-2 alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
     </button>
    <p style="color:red;"><strong>{{user_error}}</strong></p>
</div>
{% endif %}


<div id="removed_suc" style="display:none;" class="text-center p-2 my-2 alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
     </button>
    <p style="color:green;"><strong>Item removed successfully!!!</strong></p>
</div>


<section style="background-repeat:no-repeat;background-position: center center;background-size: cover;background:url({% static 'img/mainbg.png'%});">
   <div class="container">
       <div  class="row">

            <div class="col-sm-12 col-lg-2" id="main_category">
                <div id="sidebar_category" class="p-2 rounded mb-2">
                   <h4 style="color:orange;"><strong>Categories</strong></h4><hr>
                      <a  href="{% url 'products:mainshop'%}">All</a>
                   {% for category in categories  %}
                      <a id="{{category.category}}" onclick="backgroundcolor('{{title}}');" href="{% url 'products:mainshop2' category %}">{{category}}</a>
                   {% endfor %}
                </div>

                <div id="sidebar_category" class="p-2 rounded my-1">
                    <a  href="{% url 'products:type' 'Popular'%}">Popular</a>
                    <a  href="{% url 'products:type' 'Top_Seller'%}">Top Seller</a>
                    <a  href="{% url 'products:type' 'Top_rated'%}">Top rated</a>
                    <a  href="{% url 'products:type' 'Item_Deals'%}">Deals</a>
                </div>

                <div id="sidebar_category" class="p-2 rounded my-1">
                   <h4 style="color:orange;"><strong>Brand</strong></h4><hr>
                   {% for brand in brand  %}
                      <a href="{% url 'products:mainshop2' brand %}">{{brand}}</a>
                   {% endfor %}
                </div>
              
              {% if area %}
              <div id="sidebar_category" class="p-2 rounded my-1">
                   <h4 style="color:orange;"><strong>Your location</strong></h4><hr>
                   <a href="{% url 'products:mainshop2' district %}">{{district}}</a>
                   <a href="{% url 'products:mainshop2' area %}">{{area}}</a>
                </div>
              {% endif %}
            </div>
             

            <div class="col-sm-12 col-lg-10" >
               <div class="row" id="main_shop_item">
                   {% for item in items  %}
                    
                <div class="col-sm-12 col-lg-3" onmouseout="Quick_btn2('{{item.slug}}');" 
                     onmouseover="Quick_btn('{{item.slug}}');">
                    <div class=" mx-2 item_price_tage my-2 rounded" id="main_item3">
                        
                        {% if item.file %}
                        <img src="{{item.file.url}}" class="d-block w-100 rounded-top">
                        {% else %}
                        <img src="{% static 'img/item.png '%}" class="d-block w-100 rounded-top">
                        {% endif %}

                        <div class="px-1" class="">
                            <p>{{item}}</p>
                             
                             
                             {% if item.new_price %}
                             
                             <p><span style="color:red;"><strong>
                             {{item.category.currency}} </strong></span><span style="color:orange;">{{item.new_price}}</span></p>
                             {% else %}
                             <p><span style="color:red;"><strong>
                             {{item.category.currency}} </strong></span><span style="color:orange;">{{item.price}}</span></p>
                             {% endif %}

                             {% if deals %}
                            <!--{% include 'products/timer.html' %}-->
                             {% endif %}
                        </div>
                        
                        {% if item.new_price is not none %}
                        <div  style="position:absolute;top:2px; left:2px"> 
                           <small class="p-1 rounded" style="background:red;color:white;" class="round-circle;">{{item.discount}}% off</small>
                        </div>
                        {% endif %}

                        


                        {% if item.item_status == "New" %}
                        <div  style="position:absolute;top:2px; right:2px"> 
                           <small class="p-1 rounded" style="background:green;color:white;" class="round-circle;">{{item.item_status}}</small>
                        </div>
                        {% endif %}

                        <div class="item_price_tage2" id="{{item.slug}}">
                            <a style="width:100%;" 
                               class="text-center view2" id="custom_btn" href="{% url 'products:detail' item.slug %}">
                               <i class="fa fa-eye" aria-hidden="true"></i>
                               Quick view
                             </a>

                                
                               <div id="edit_delete" class="p-2">

                                {% if user.is_superuser %}
                                  <a class="close"  onclick="delete_shop_item('{% url 'products:delete_item' item.slug %}');" href="javascript:void(0);">
                                    <i class="fa fa-trash" aria-hidden="true"></i>
                                  </a>
                                 

                                  <a class="close" onclick="edit_main_shop_item('{% url 'products:edit' item.slug %}');" href="javascript:void(0);">
                                    <i class="fas fa-edit"></i>
                                  </a>
                                  {% endif %}

                                 {% if item.user == request.user%}
                                  <a id="make_deal" class="p-1 rounded" href="{% url 'products:deal_payment_form' item.slug %}">Make deal</a>
                                  {% endif %}
                               </div>
                               
                        </div>
                    </div>
                </div>

               {% empty %}
                   <div class="col-sm-12">
                      {% include 'index/error.html' %}
                   </div>
               {% endfor %}
               </div>

<!--________________pagination_______________________________-->
           <div class="col-sm-12 my-4">
               <div class="pagination">
                <span class="step-links">
                    {% if items.has_previous %}
                        <a href="?page=1">&laquo;</a>
                        <a href="?page={{ items.previous_page_number }}">
                          <i class="fa fa-arrow-left" aria-hidden="true"></i>
                        </a>

                    {% endif %}

                    <span class="current">
                        Page {{ items.number }} of {{items.paginator.num_pages }}.
                    </span>

                    {% if items.has_next %}
                        <a href="?page={{items.next_page_number }}">
                          <i class="fa fa-arrow-right" aria-hidden="true"></i>
                        </a>
                        <a href="?page={{items.paginator.num_pages }}">&raquo;</a>
                    {% endif %}
                </span>
            </div>
           </div>
<!--__________________________________________________________-->
            </div>
        </div>


   </div>
</section>

{% if brand %}
{% include 'products/brand.html'%}
{% endif %}

{% endblock %}

products/templates/products/shop2.html
    
                   {% for item in items  %}
                <div class="col-sm-12 col-lg-3" onmouseout="Quick_btn2('{{item.slug}}');" 
                     onmouseover="Quick_btn('{{item.slug}}');">
                    <div class=" mx-2 item_price_tage my-2 rounded" id="main_item3">
                    
                        {% if item.file %}
                        <img src="{{item.file.url}}" class="d-block w-100 rounded-top">
                        {% else %}
                        <img src="{% static 'img/item.png '%}" class="d-block w-100 rounded-top">
                        {% endif %}
                        <div class="px-1" class="">
                            <p>{{item}}</p>
                             
                             
                             {% if item.new_price %}
                             
                             <p><span style="color:red;"><strong>
                             {{item.category.currency}} </strong></span>{{item.new_price}}</p>
                             {% else %}
                             <p><span style="color:red;"><strong>
                             {{item.category.currency}} </strong></span>{{item.price}}</p>
                             {% endif %}

                        </div>
                        
                        {% if item.new_price is not none %}
                        <div  style="position:absolute;top:2px; left:2px"> 
                           <small class="p-1" style="background:red;color:white;" class="round-circle;">{{item.discount}}% off</small>
                        </div>
                        {% endif %}

                        <div class="item_price_tage2" id="{{item.slug}}">
                           
                            <a style="width:100%;" 
                               class="text-center view2" id="custom_btn" href="{% url 'products:detail' item.slug %}">
                               <i class="fa fa-eye" aria-hidden="true"></i>
                               Quick view
                             </a>

                               {% if user.is_superuser %} 
                               <div id="edit_delete" class="p-2">
                                  <a class="close"  onclick="delete_shop_item('{% url 'products:delete_item' item.slug %}');" href="javascript:void(0);">
                                    <i class="fa fa-trash" aria-hidden="true"></i>
                                  </a>
                                
                                  <a class="close" onclick="edit_main_shop_item('{% url 'products:edit' item.slug %}');" href="javascript:void(0);">
                                    <i class="fas fa-edit"></i>
                                  </a>
                                  <a style="background:white;" class="p-1 rounded" href="{% url 'products:deal_payment_form' item.slug %}">Make deal</a>
                               </div>
                               {% endif %}
                        </div>
                    </div>
                </div>
               {% empty %}
                   <div class="col-sm-12">
                      {% include 'index/error.html' %}
                   </div>
               {% endfor %}
               